// Generated by tools/export_rules.mjs from the web game (src/data, src/content, src/game/daily.js). Don’t edit by hand.
using System.Collections.Generic;

namespace Sweepstakes
{
    public sealed class Table
    {
        public readonly string Id, Name, Blurb; public readonly int W, H, M, Gems; public readonly double Lim, Prog, Min, Cap, Cost;
        public Table(string id, string name, int w, int h, int m, int gems, double lim, double prog, double min, double cap, double cost, string blurb)
        { Id = id; Name = name; W = w; H = h; M = m; Gems = gems; Lim = lim; Prog = prog; Min = min; Cap = cap; Cost = cost; Blurb = blurb; }
    }
    public sealed class GemTier { public readonly string K, Name; public readonly double X, W; public GemTier(string k, double x, double w, string name) { K = k; X = x; W = w; Name = name; } }
    public sealed class Style { public readonly string Who; public readonly double Boom, Lo, Hi; public Style(string who, double boom, double lo, double hi) { Who = who; Boom = boom; Lo = lo; Hi = hi; } }
    public sealed class GoldenBoard
    {
        public readonly string Key, Mines, Open; public readonly int Number; public readonly int[] GemAt; public readonly double[] GemX; public readonly string[] FriendWho; public readonly double[] FriendMult;
        public GoldenBoard(string key, int number, string mines, string open, int[] gemAt, double[] gemX, string[] friendWho, double[] friendMult)
        { Key = key; Number = number; Mines = mines; Open = open; GemAt = gemAt; GemX = gemX; FriendWho = friendWho; FriendMult = friendMult; }
    }
    public sealed class GoldenRun
    {
        public readonly string Key, Why; public readonly string[] Moves; public readonly int Revealed; public readonly double Mult;
        public GoldenRun(string key, string[] moves, int revealed, double mult, string why) { Key = key; Moves = moves; Revealed = revealed; Mult = mult; Why = why; }
    }

    public static class Rules
    {
        public const long START = 1000;
        public const double BOOST = 1.2, CLEAR = 1.25, GOLDEN = 0.08, CASINO = 600000000000000.0;
        public static readonly int[] LADDER = { 2, 5, 10, 25, 100 };
        public static readonly Table[] TABLES = {
            new Table("penny", "Penny Patch", 6, 6, 5, 1, 3.0, 0.4, 10.0, 1000.0, 0.0, "Training wheels. Nan plays here."),
            new Table("den", "Dodgy Den", 8, 8, 11, 2, 6.0, 0.3, 200.0, 20000.0, 18000.0, "Sticky floor. Sticky tiles."),
            new Table("alley", "Back Alley", 9, 9, 17, 2, 12.0, 0.25, 4000.0, 400000.0, 1200000.0, "Cash only. No questions."),
            new Table("roller", "High Rollers", 10, 10, 24, 3, 25.0, 0.2, 80000.0, 8000000.0, 75000000.0, "Velvet rope, velvet mines."),
            new Table("whale", "Whale Pit", 12, 12, 38, 4, 60.0, 0.15, 1600000.0, 160000000.0, 4500000000.0, "Where fortunes go for a swim."),
            new Table("abyss", "The Abyss", 14, 14, 56, 5, 200.0, 0.12, 32000000.0, 3200000000.0, 85000000000.0, "It stares back.")
        };
        public static readonly GemTier[] GEMS = { new GemTier("gem", 1.2, 0.6, "Gem"), new GemTier("ruby", 1.5, 0.28, "Ruby"), new GemTier("diamond", 2.0, 0.1, "Diamond"), new GemTier("jackpot", 5.0, 0.02, "JACKPOT") };
        public static readonly Dictionary<string, string> FRIENDS = new Dictionary<string, string> { { "dave", "Big Dave" }, { "tash", "Tash" }, { "kev", "Kev from work" }, { "nan", "Nan" }, { "priya", "Priya" } };
        public static readonly string[] SURE = { "Are you sure?", "Are you SURE sure?", "Mate. Are you actually sure?", "This is where sensible people stop.", "Nan is crying. Are you sure?" };
        public static readonly string[] QUIPS = {
            "my mum plays this game",
            "my mum plays this game. she’s better than you.",
            "alexa, add condoms to my shopping cart",
            "alexa, how many mines is too many",
            "hey siri, is the goblin single",
            "ok google, what is a tile, really",
            "be gay, do minesweeper",
            "gay rights. left-click rights.",
            "bisexual lighting: engaged",
            "pronouns: dig/digger",
            "the flag is non-binary and thriving",
            "the bomb is going through a phase",
            "he’s just a little guy (the bomb)",
            "the bomb has a crush on you",
            "flag? I barely know her",
            "mine? I barely know her",
            "cash out? I barely know her",
            "the tiles are whispering again",
            "I have been a tile since 1997",
            "hello from inside the board",
            "the goblin knows your postcode",
            "bees?",
            "a pigeon has entered the casino",
            "I licked the 7. it tasted like 8",
            "the 3 and the 5 are dating",
            "the 8 is going through a divorce",
            "the number 4 owes me money",
            "your nan is watching. wave.",
            "the cat is the house edge",
            "the floor is lava. the lava is mines.",
            "do not perceive the bomb",
            "there is a horse in the walls",
            "a crab is managing your portfolio",
            "the casino is three raccoons in a coat",
            "who left soup on the roulette",
            "I am the tile now",
            "mines are just angry pebbles",
            "your aura just went up 400",
            "drink some water, you beautiful gremlin",
            "dad, if you’re reading this, it’s educational",
            "not gambling. aggressively counting.",
            "that tile looked at you funny",
            "brought to you by a damp sock",
            "sorry, the ghost was using the mouse",
            "the wifi password is mine123",
            "eat the rich (tiles)",
            "you’re doing amazing, sweetie",
            "slay. no notes. ok one note.",
            "mother is mothering",
            "girlboss, gaslight, gamble",
            "the bots have unionised",
            "the bots are kissing. give them a minute.",
            "this board is haunted (affectionate)",
            "mum says it’s my turn on the minesweeper",
            "emotionally, I am a 3",
            "spiritually, I am a flag",
            "I’m not addicted, I’m committed",
            "camp is a lifestyle. so is losing.",
            "out of the closet, into the casino",
            "gay agenda: dig, cash out, brunch",
            "queer eye for the safe tile",
            "accidentally liked a tile from 2019",
            "pride month never ends in here",
            "left click is my love language",
            "the googly eyes are load-bearing",
            "tell your mum I said hi",
            "the moon is just a big safe tile",
            "your houseplants are proud of you",
            "a frog has entered the chat",
            "mines hate this one weird trick",
            "the duck is not a metaphor",
            "is it gay to clear a board? (yes)",
            "certified tile licker",
            "main character energy detected",
            "who let the goblin cook",
            "you’ve been visited by the gay frog of fortune",
            "kiss the bomb. (do not kiss the bomb)",
            "error 404: chill not found",
            "today’s lucky number is a mine",
            "this game is gluten free",
            "your fbi agent just cashed out",
            "nan is speedrunning",
            "vote boom, get boom",
            "the mines have a better manifesto than your lot",
            "thou shalt cash out",
            "blessed are the cashed out",
            "pray for a 1",
            "water into wine? I turned 1,000 into 12",
            "the ducks have formed a union",
            "the kitten owns the casino now",
            "change the battery, coward",
            "the smoke detector knows what you did",
            "answer the door. or don’t. the door knows",
            "a duck house, on expenses",
            "tax the ducks"
        };
        public static readonly Dictionary<string, string[][]> LINES = new Dictionary<string, string[][]> {
            { "daily_nudge", new[] { new[] { "dave", "did the daily. ×{x}. genius behaviour, frankly" }, new[] { "tash", "daily’s up. ×{x}. not saying I’m better than you but I am" }, new[] { "kev", "today’s daily: ×{x}. told my manager. he did not care" }, new[] { "priya", "daily done. ×{x}. your move" }, new[] { "nan", "I did the daily puzzle love. ×{x}. Is that good x" } } },
            { "daily_nudge_boom", new[] { new[] { "dave", "the daily blew up in my face. we don’t talk about it" }, new[] { "tash", "the daily is rigged. one dig. ONE" }, new[] { "kev", "exploded on the daily before my coffee. great start to the day" }, new[] { "priya", "daily: boom. logging off forever (back in 5)" } } },
            { "daily_top", new[] { new[] { "dave", "how. HOW" }, new[] { "tash", "screenshot or it didn’t happen" }, new[] { "nan", "Top of the class! I’m telling everyone at bingo x" }, new[] { "kev", "printing this for the office fridge" }, new[] { "priya", "fine. FINE. tomorrow you’re going down" } } },
            { "daily_ok", new[] { new[] { "priya", "×{x}. respectable. not good. respectable" }, new[] { "dave", "×{x}? I’ve seen better. from Nan" }, new[] { "tash", "not bad for someone who digs like that" }, new[] { "kev", "×{x} is my new lucky number. I don’t have a lucky number" }, new[] { "nan", "Well done love, ×{x}! Have a biscuit x" } } },
            { "daily_boom", new[] { new[] { "dave", "HAHAHAHA the daily got you" }, new[] { "nan", "Never mind love, there’s always tomorrow x" }, new[] { "kev", "the daily got me too once. solidarity" }, new[] { "tash", "one go. ONE. and you spent it like that" }, new[] { "priya", "see you tomorrow, champ" } } },
            { "achievement", new[] { new[] { "tash", "achievement unlocked: being insufferable about it" }, new[] { "dave", "you get a little badge for that? cute" }, new[] { "nan", "Ooh a trophy! I’ll put it on the fridge x" }, new[] { "kev", "I have zero of those. zero" }, new[] { "priya", "“{name}”. adding it to your obituary" } } },
            { "hello", new[] { new[] { "dave", "right, who’s in" }, new[] { "tash", "oh here we go again" }, new[] { "nan", "Don’t stay up too late love x" }, new[] { "priya", "house rules: no crying at the table" }, new[] { "kev", "I brought snacks. the snacks are mines" }, new[] { "nan", "Is this the gambling one? Lovely x" }, new[] { "dave", "right, you degenerates, who’s in" }, new[] { "tash", "back again? your bank must be thrilled" }, new[] { "kev", "told the wife I’m at the gym" }, new[] { "priya", "welcome back to bad decisions" } } },
            { "deal_big", new[] { new[] { "dave", "{stake} on ONE board? absolute scenes" }, new[] { "tash", "oh we’re doing this are we" }, new[] { "kev", "my palms are sweating and I’m not even playing" }, new[] { "priya", "screenshotting this for evidence" }, new[] { "nan", "Be careful love x" }, new[] { "tash", "hold my earrings" }, new[] { "dave", "absolute madman" }, new[] { "kev", "you’re going to lose that, aren’t you" }, new[] { "tash", "oh for god’s sake" }, new[] { "priya", "your pension just called. it was crying" } } },
            { "boom", new[] { new[] { "dave", "BAHAHAHA" }, new[] { "tash", "that tile had a FACE on it" }, new[] { "kev", "F" }, new[] { "priya", "that mine had a family" }, new[] { "nan", "Was that thunder love? x" }, new[] { "dave", "you clicked that with your whole chest" }, new[] { "tash", "down {stake}. thoughts and prayers" }, new[] { "kev", "the bomb said “ok” and then did a crime" }, new[] { "priya", "the googly eyes saw everything" }, new[] { "dave", "you absolute muppet" }, new[] { "tash", "oh you plonker" }, new[] { "nan", "Oh bugger x" }, new[] { "kev", "bollocks. sorry. but bollocks" }, new[] { "priya", "skill issue" }, new[] { "dave", "clicked it like it owed you money" } } },
            { "cash_small", new[] { new[] { "tash", "bok bok bok" }, new[] { "dave", "{profit}. that’s like three meal deals" }, new[] { "priya", "sensible. boring, but sensible" }, new[] { "nan", "I’ll put it in the biscuit tin for you x" }, new[] { "kev", "respect the bag, however small" }, new[] { "dave", "what is that, a tip?" }, new[] { "tash", "wow. a whole sandwich" }, new[] { "kev", "cowardly. but profitable" } } },
            { "cash_big", new[] { new[] { "dave", "+{profit}?! drinks are on you" }, new[] { "priya", "that’s generational wealth (fake)" }, new[] { "nan", "Well done darling! Don’t spend it all on scratchcards x" }, new[] { "tash", "buy a horse. a small one. for me" }, new[] { "kev", "naming my firstborn {profit}" }, new[] { "dave", "you jammy git" }, new[] { "tash", "you lucky cow" }, new[] { "kev", "buy me a pint, you tight sod" } } },
            { "clear", new[] { new[] { "kev", "CLEAN SWEEP. I need a lie down" }, new[] { "dave", "not one mine. who ARE you" }, new[] { "priya", "the board is naked now. look away" }, new[] { "nan", "Very tidy love, like your grandad’s shed x" }, new[] { "tash", "the full clear. disgusting. iconic" }, new[] { "dave", "show-off" }, new[] { "tash", "you look smug. I can tell from here" } } },
            { "don_offer", new[] { new[] { "dave", "do it. do it. do it." }, new[] { "tash", "the voices say yes. the voices are me" }, new[] { "nan", "I wouldn’t love" }, new[] { "kev", "I’m watching through my fingers" }, new[] { "priya", "the maths says walk away. I say nothing" }, new[] { "dave", "don’t be a wuss" }, new[] { "tash", "what’s the worst that could happen (everything)" }, new[] { "kev", "my therapist says I shouldn’t watch this" } } },
            { "don_win", new[] { new[] { "dave", "NO WAY" }, new[] { "tash", "ICON. LEGEND. MOTHER." }, new[] { "priya", "the odds said no. you said yes" }, new[] { "kev", "I just stood up at my desk" }, new[] { "nan", "Ooh lovely x" } } },
            { "don_lose", new[] { new[] { "dave", "oh no. oh no no no" }, new[] { "tash", "rip to your entire run" }, new[] { "nan", "Never mind love. Money is just paper with ghosts in x" }, new[] { "kev", "pour one out" }, new[] { "dave", "well that was bloody stupid" }, new[] { "tash", "HAHAHAHA. sorry. HAHAHA" }, new[] { "kev", "that’s a crime against money" } } },
            { "bust", new[] { new[] { "nan", "Come round for tea love, I’ll do you a sandwich x" }, new[] { "dave", "from hero to zero" }, new[] { "tash", "changing the group name to “skint”" }, new[] { "priya", "respectfully: lmao" }, new[] { "kev", "the goblin is going through your bins now" }, new[] { "dave", "skint. absolutely skint" }, new[] { "tash", "you gambled the rent, didn’t you" }, new[] { "kev", "who’s telling your mum" }, new[] { "priya", "rock bottom has a basement. welcome" } } },
            { "buy", new[] { new[] { "kev", "ooh shiny" }, new[] { "priya", "investing in yourself, love that" }, new[] { "dave", "what does that even do" }, new[] { "nan", "Is that one of those NFTs love? x" }, new[] { "tash", "spending money to make money. classic" }, new[] { "dave", "you got mugged off" }, new[] { "tash", "that’s a rip-off and you know it" } } },
            { "addon", new[] { new[] { "kev", "ooh a little card" }, new[] { "tash", "that card is doing something illegal" }, new[] { "priya", "that card is giving main character" }, new[] { "dave", "is that one of them lucky cards" } } },
            { "unlock", new[] { new[] { "dave", "new table who dis" }, new[] { "tash", "moving up in the world" }, new[] { "kev", "the carpet in there is sticky in a good way" }, new[] { "nan", "Is that the one with the nice carpet? x" } } },
            { "ascend", new[] { new[] { "dave", "ASCENSION? in THIS economy?" }, new[] { "priya", "more mines, more money. sounds legal" }, new[] { "kev", "you’re glowing. is that radiation" }, new[] { "tash", "the tables look angrier already" } } },
            { "streak", new[] { new[] { "tash", "{streak} in a row?? on fire" }, new[] { "dave", "heater. absolute heater" }, new[] { "kev", "don’t jinx it don’t jinx it" }, new[] { "priya", "statistically this has to end. not my problem though" }, new[] { "dave", "don’t get cocky" } } },
            { "coward", new[] { new[] { "tash", "the robot chickened out lmao" }, new[] { "nan", "The robot has more sense than your grandad x" } } },
            { "yolo", new[] { new[] { "dave", "the robot is gambling now. we’ve created a monster" }, new[] { "tash", "the robot is in its villain era" } } },
            { "flip_win", new[] { new[] { "priya", "coin respected you" }, new[] { "nan", "I always pick heads love. Or tails. One of them x" } } },
            { "flip_lose", new[] { new[] { "tash", "the coin hates you specifically" }, new[] { "kev", "it was always going to be the other side" }, new[] { "dave", "the coin mugged you off" }, new[] { "tash", "unlucky. no actually, you’re just bad" } } },
            { "shield", new[] { new[] { "priya", "saved by the shield!" }, new[] { "dave", "plot armour" } } },
            { "fuse", new[] { new[] { "dave", "the bomb went “pfft” lmao" }, new[] { "kev", "damp squib. literally" } } },
            { "gem", new[] { new[] { "tash", "SHINY" }, new[] { "kev", "a gem! like you" }, new[] { "priya", "that’s going in the vault" }, new[] { "nan", "Ooh sparkly x" }, new[] { "dave", "pocket it before the goblin sees" } } },
            { "jackpot", new[] { new[] { "dave", "JACKPOT. I’m crying in a Wetherspoons" }, new[] { "tash", "SCREAMING. CRYING. THROWING UP." }, new[] { "nan", "Ooh, that’s the fruit machine noise! x" }, new[] { "dave", "you jammy, jammy sod" } } },
            { "golden", new[] { new[] { "priya", "a golden board?? manifest it" }, new[] { "kev", "everything is shiny and I’m scared" } } },
            { "levelup", new[] { new[] { "priya", "level up! growth!" }, new[] { "nan", "Well done love, I’ve told the whole street x" }, new[] { "kev", "you’re officially a {rank} now" }, new[] { "dave", "{rank}? put it on your CV" }, new[] { "dave", "levelling up at gambling. your mum must be so proud" } } },
            { "spin", new[] { new[] { "tash", "spin the wheel spin the wheel" }, new[] { "kev", "the wheel is my higher power now" } } },
            { "casino", new[] { new[] { "nan", "My grandchild owns a CASINO x" }, new[] { "dave", "I’m telling everyone I knew you before" }, new[] { "tash", "free drinks forever right? right??" } } },
            { "odd_smoke", new[] { new[] { "kev", "is that the smoke alarm" }, new[] { "nan", "That’s the smoke alarm love, it wants a new battery x" }, new[] { "tash", "that chirp is going to live in my head rent free" }, new[] { "dave", "it’ll do that once a minute for three weeks. it’s tradition" }, new[] { "priya", "we are all being haunted by one small battery" }, new[] { "dave", "they only ever run out at 3am. it’s in the contract" } } },
            { "odd_alarm", new[] { new[] { "nan", "Who’s burnt the toast? x" }, new[] { "tash", "the smoke alarm is screaming. so am I" }, new[] { "dave", "open a window and wave a tea towel. the British way" } } },
            { "odd_knock", new[] { new[] { "dave", "don’t answer it. it’s the bailiffs" }, new[] { "tash", "knock knock. who’s there. your debts" }, new[] { "kev", "pretend you’re not in" }, new[] { "nan", "Is that the man about the gutters? x" } } },
            { "odd_doorbell", new[] { new[] { "dave", "don’t answer it. it’s the bailiffs" }, new[] { "tash", "expecting someone? ;)" }, new[] { "priya", "nobody rings a doorbell anymore. it’s either the police or a cult" } } },
            { "odd_phone", new[] { new[] { "nan", "Is that the landline? Nobody rings the landline x" }, new[] { "dave", "it’s a scammer. it’s always a scammer" }, new[] { "kev", "let it ring. it’s 2026" } } },
            { "odd_kittens", new[] { new[] { "tash", "KITTENS??" }, new[] { "nan", "Has someone left kittens on the step? x" }, new[] { "priya", "drop everything. kittens" }, new[] { "dave", "is that a kitten or the wifi router dying" } } },
            { "odd_ducks", new[] { new[] { "priya", "why are there ducks" }, new[] { "dave", "the ducks are unionising" }, new[] { "kev", "I hear the ducks before the bombs now" }, new[] { "tash", "the ducks know something" } } },
            { "odd_duck", new[] { new[] { "priya", "why is there a duck" }, new[] { "dave", "quack" }, new[] { "nan", "Save your crusts for the ducks love x" } } },
            { "odd_squeak", new[] { new[] { "kev", "was that the dog or you" }, new[] { "tash", "who’s squeezing the toy" }, new[] { "dave", "the dog’s winning more than you" } } },
            { "odd_carAlarm", new[] { new[] { "dave", "is that my car" }, new[] { "kev", "car alarms have never once stopped a crime" }, new[] { "tash", "some poor sod’s car is having a breakdown" }, new[] { "dave", "turn it off, you absolute weapon" } } },
            { "odd_microwave", new[] { new[] { "tash", "who’s microwaving fish at this hour" }, new[] { "dave", "your pizza’s done" } } },
            { "odd_buzz", new[] { new[] { "priya", "your phone’s going" }, new[] { "kev", "is that the bank calling" } } },
            { "odd_kettle", new[] { new[] { "nan", "Ooh put one on for me love x" }, new[] { "priya", "tea break?? mid-game??" } } },
            { "odd_fart", new[] { new[] { "tash", "who did that" }, new[] { "kev", "not me" }, new[] { "dave", "better out than in" }, new[] { "dave", "whoever smelt it dealt it" }, new[] { "tash", "kev that’s disgusting" }, new[] { "kev", "IT WASN’T ME" } } },
            { "odd_creak", new[] { new[] { "dave", "did anyone else hear that door" }, new[] { "nan", "Is somebody there? x" } } },
            { "odd_meow", new[] { new[] { "nan", "Has someone fed the cat? x" }, new[] { "tash", "KITTY" } } },
            { "chirp_again", new[] { new[] { "tash", "it’s still chirping" }, new[] { "dave", "CHANGE. THE. BATTERY." }, new[] { "kev", "I can hear it through the chat somehow" }, new[] { "nan", "Use the kitchen chair love, not the wobbly one x" }, new[] { "priya", "that chirp has more staying power than my last three relationships" }, new[] { "tash", "CHANGE THE BLOODY BATTERY" } } },
            { "battery_ok", new[] { new[] { "dave", "silence. beautiful silence" }, new[] { "tash", "a hero. a DIY hero" }, new[] { "nan", "Your grandad never changed one in forty years x" }, new[] { "kev", "was it a 9 volt. I could feel it was a 9 volt" } } },
            { "battery_fall", new[] { new[] { "dave", "I heard that from here" }, new[] { "tash", "are you alive" }, new[] { "nan", "Not the wobbly chair! x" }, new[] { "priya", "the chirp won. the chirp always wins" }, new[] { "kev", "arse over tit. a classic" }, new[] { "dave", "did you land on your arse or your face" } } },
            { "door_good", new[] { new[] { "nan", "See, it pays to answer the door x" }, new[] { "dave", "free stuff from the door. the door is your friend now" }, new[] { "kev", "I never answer the door and look at me" } } },
            { "door_bad", new[] { new[] { "dave", "told you not to answer it" }, new[] { "tash", "the door giveth and the door taketh away" }, new[] { "priya", "and that’s why I live in a cupboard" }, new[] { "kev", "lesson learned: never open the door" }, new[] { "dave", "absolute pillocks" }, new[] { "tash", "they took the LAMP?? the bloody cheek" } } },
            { "door_weird", new[] { new[] { "priya", "what just happened" }, new[] { "kev", "I have questions" }, new[] { "tash", "your door is cursed and I love it" }, new[] { "nan", "Was it the nice young man with the leaflets? x" } } },
            { "phone", new[] { new[] { "dave", "who was it" }, new[] { "nan", "Was it me? I can’t remember if I rang x" }, new[] { "tash", "you answered a phone call? brave" }, new[] { "kev", "I haven’t answered a call since 2019" } } },
            { "kitten_pet", new[] { new[] { "tash", "PROTECT THE KITTEN" }, new[] { "nan", "Give it a bit of ham love x" }, new[] { "priya", "the kitten is the CEO now" }, new[] { "kev", "I would die for that kitten" }, new[] { "dave", "put the kitten on the payroll" } } },
            { "kitten_gone", new[] { new[] { "tash", "you let the kitten LEAVE??" }, new[] { "priya", "a kitten walked past and you didn’t even look. monster" }, new[] { "nan", "It’ll be back when it’s hungry love x" }, new[] { "dave", "you heartless git" } } },
            { "toast", new[] { new[] { "nan", "Scrape the black bits off love, it’s fine x" }, new[] { "dave", "burnt toast is just toast with ambition" }, new[] { "kev", "I like it burnt. I’m not well" }, new[] { "priya", "the tea towel wave. a British classic" } } },
            { "raffle_win", new[] { new[] { "nan", "I’ve never won a raffle in my life! x" }, new[] { "dave", "roof funded. children saved. legend" }, new[] { "tash", "rigged. love it" } } },
            { "raffle_lose", new[] { new[] { "kev", "the roof thanks you" }, new[] { "dave", "charity is its own reward. the reward is nothing" }, new[] { "priya", "it’s for the kids. the kids won" } } },
            { "duck_start", new[] { new[] { "dave", "COME ON THE YELLOW ONE" }, new[] { "tash", "my money’s on whichever one looks the most unhinged" }, new[] { "kev", "the ducks are on something. I can tell" }, new[] { "nan", "Which one’s ours love? x" }, new[] { "priya", "I’ve got a tenner on the slowest one. for the story" } } },
            { "duck_win", new[] { new[] { "dave", "THE DUCK DID IT" }, new[] { "tash", "that duck deserves a knighthood" }, new[] { "nan", "Lovely ducks x" }, new[] { "kev", "I’m crying. over a duck" }, new[] { "priya", "bread for that duck. all of the bread" } } },
            { "duck_lose", new[] { new[] { "dave", "that duck threw the race" }, new[] { "tash", "your duck stopped for a snack" }, new[] { "kev", "the duck was paid off. I’ve seen it before" }, new[] { "priya", "never trust a duck" }, new[] { "nan", "Never mind love, they’re all winners really x" }, new[] { "dave", "useless bloody duck" }, new[] { "tash", "that duck can get stuffed. with orange sauce" } } }
        };
        public static readonly int[] DAILY_EPOCH = { 2026, 10, 6 };
        public const string DAILY_TABLE = "alley", DAILY_SEED = "sweepstakes-daily-", DAILY_CHAT_SEED = "sweepstakes-chat-";
        public const double DAILY_LIMIT = 100.0, DAILY_PRIZE = 0.3;
        public const int DAILY_GEMS = 3;
        public static readonly Style[] DAILY_STYLES = { new Style("nan", 0.0, 1.2, 2.6), new Style("kev", 0.2, 1.1, 3.5), new Style("tash", 0.3, 1.8, 8.0), new Style("priya", 0.25, 2.5, 10.0), new Style("dave", 0.45, 3.0, 18.0) };
        public static readonly GoldenBoard[] GOLDEN_BOARDS = {
            new GoldenBoard("2026-10-06", 1, "000001000000000000100001000000011100100000110000101100100000000000001000000001110", "111110000111110000011110000011100000011100000000000000000000000000000000000000000", new[] { 25, 46, 58 }, new[] { 1.5, 1.5, 1.2 }, new[] { "nan", "kev", "tash", "priya", "dave" }, new[] { 2.01, 1.18, 3.9, 9.49, 12.02 }),
            new GoldenBoard("2026-12-25", 81, "000000001100011101001000000000000000000010001101100000000100000000010001011000000", "000000000000000000000001110000001110000001110000001110000001110000001110000001110", new[] { 21, 56, 66 }, new[] { 1.5, 1.2, 1.2 }, new[] { "nan", "kev", "tash", "priya", "dave" }, new[] { 1.89, 2.78, 5.32, 0.0, 0.0 }),
            new GoldenBoard("2027-02-28", 146, "000000101000010110001100010000000010000000000000000011000000000010000000001010111", "111100000111100000110011100111111100111111100111111100111111100001111100000000000", new[] { 14, 43, 71 }, new[] { 1.5, 1.2, 1.5 }, new[] { "nan", "kev", "tash", "priya", "dave" }, new[] { 1.56, 1.69, 1.98, 8.76, 0.0 }),
            new GoldenBoard("2030-01-01", 1184, "001100011010110000000000000000000010000000000110010001000000101010000001001000000", "000000000000000000111111100111111100111111100000000000000000000000000000000000000", new[] { 50, 51, 52 }, new[] { 2.0, 1.2, 1.5 }, new[] { "nan", "kev", "tash", "priya", "dave" }, new[] { 1.51, 1.24, 2.06, 2.51, 0.0 })
        };
        public static readonly GoldenRun[] GOLDEN_RUNS = {
            new GoldenRun("2026-10-06", new[] { "safe", "safe", "safe", "gem", "safe", "safe", "safe", "safe", "safe", "gem", "safe", "safe" }, 32, 1.9227272727272724, "cash"),
            new GoldenRun("2026-12-25", new[] { "safe", "gem", "safe", "safe", "safe", "safe", "safe", "r2", "r2", "safe", "safe", "safe" }, 38, 4.087360365073582, "cash"),
            new GoldenRun("2027-02-28", new[] { "safe", "safe", "safe", "safe", "safe", "r2", "boom" }, 52, 0.0, "boom"),
            new GoldenRun("2030-01-01", new[] { "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe" }, 33, 1.069767441860465, "cash")
        };
    }
}
