// Generated by tools/export_rules.mjs from the web game (src/data, src/content, src/game/daily.js). Don’t edit by hand.
package sweepstakes

data class Table(val id: String, val name: String, val w: Int, val h: Int, val m: Int, val gems: Int, val lim: Double,
                 val prog: Double, val min: Double, val cap: Double, val cost: Double, val blurb: String)
data class GemTier(val k: String, val x: Double, val w: Double, val name: String)
data class Style(val who: String, val boom: Double, val lo: Double, val hi: Double)
data class GoldenBoard(val key: String, val number: Int, val mines: String, val open: String, val gems: List<Pair<Int, Double>>, val friends: List<Pair<String, Double>>)
data class GoldenRun(val key: String, val moves: List<String>, val revealed: Int, val mult: Double, val why: String)

object Rules {
    const val START = 1000L
    const val BOOST = 1.2
    const val CLEAR = 1.25
    const val GOLDEN = 0.08
    const val CASINO = 600000000000000.0
    val LADDER = listOf(2, 5, 10, 25, 100)
    val TABLES = listOf(
        Table("penny", "Penny Patch", 6, 6, 5, 1, 3.0, 0.4, 10.0, 1000.0, 0.0, "Training wheels. Nan plays here."),
        Table("den", "Dodgy Den", 8, 8, 11, 2, 6.0, 0.3, 200.0, 20000.0, 18000.0, "Sticky floor. Sticky tiles."),
        Table("alley", "Back Alley", 9, 9, 17, 2, 12.0, 0.25, 4000.0, 400000.0, 1200000.0, "Cash only. No questions."),
        Table("roller", "High Rollers", 10, 10, 24, 3, 25.0, 0.2, 80000.0, 8000000.0, 75000000.0, "Velvet rope, velvet mines."),
        Table("whale", "Whale Pit", 12, 12, 38, 4, 60.0, 0.15, 1600000.0, 160000000.0, 4500000000.0, "Where fortunes go for a swim."),
        Table("abyss", "The Abyss", 14, 14, 56, 5, 200.0, 0.12, 32000000.0, 3200000000.0, 85000000000.0, "It stares back."))
    val GEMS = listOf(GemTier("gem", 1.2, 0.6, "Gem"), GemTier("ruby", 1.5, 0.28, "Ruby"), GemTier("diamond", 2.0, 0.1, "Diamond"), GemTier("jackpot", 5.0, 0.02, "JACKPOT"))
    val FRIENDS = mapOf("dave" to "Big Dave", "tash" to "Tash", "kev" to "Kev from work", "nan" to "Nan", "priya" to "Priya")
    val SURE = listOf("Are you sure?", "Are you SURE sure?", "Mate. Are you actually sure?", "This is where sensible people stop.", "Nan is crying. Are you sure?")
    val QUIPS = listOf(
        "my mum plays this game",
        "my mum plays this game. she’s better than you.",
        "alexa, add condoms to my shopping cart",
        "alexa, how many mines is too many",
        "hey siri, is the goblin single",
        "ok google, what is a tile, really",
        "be gay, do minesweeper",
        "gay rights. left-click rights.",
        "bisexual lighting: engaged",
        "pronouns: dig/digger",
        "the flag is non-binary and thriving",
        "the bomb is going through a phase",
        "he’s just a little guy (the bomb)",
        "the bomb has a crush on you",
        "flag? I barely know her",
        "mine? I barely know her",
        "cash out? I barely know her",
        "the tiles are whispering again",
        "I have been a tile since 1997",
        "hello from inside the board",
        "the goblin knows your postcode",
        "bees?",
        "a pigeon has entered the casino",
        "I licked the 7. it tasted like 8",
        "the 3 and the 5 are dating",
        "the 8 is going through a divorce",
        "the number 4 owes me money",
        "your nan is watching. wave.",
        "the cat is the house edge",
        "the floor is lava. the lava is mines.",
        "do not perceive the bomb",
        "there is a horse in the walls",
        "a crab is managing your portfolio",
        "the casino is three raccoons in a coat",
        "who left soup on the roulette",
        "I am the tile now",
        "mines are just angry pebbles",
        "your aura just went up 400",
        "drink some water, you beautiful gremlin",
        "dad, if you’re reading this, it’s educational",
        "not gambling. aggressively counting.",
        "that tile looked at you funny",
        "brought to you by a damp sock",
        "sorry, the ghost was using the mouse",
        "the wifi password is mine123",
        "eat the rich (tiles)",
        "you’re doing amazing, sweetie",
        "slay. no notes. ok one note.",
        "mother is mothering",
        "girlboss, gaslight, gamble",
        "the bots have unionised",
        "the bots are kissing. give them a minute.",
        "this board is haunted (affectionate)",
        "mum says it’s my turn on the minesweeper",
        "emotionally, I am a 3",
        "spiritually, I am a flag",
        "I’m not addicted, I’m committed",
        "camp is a lifestyle. so is losing.",
        "out of the closet, into the casino",
        "gay agenda: dig, cash out, brunch",
        "queer eye for the safe tile",
        "accidentally liked a tile from 2019",
        "pride month never ends in here",
        "left click is my love language",
        "the googly eyes are load-bearing",
        "tell your mum I said hi",
        "the moon is just a big safe tile",
        "your houseplants are proud of you",
        "a frog has entered the chat",
        "mines hate this one weird trick",
        "the duck is not a metaphor",
        "is it gay to clear a board? (yes)",
        "certified tile licker",
        "main character energy detected",
        "who let the goblin cook",
        "you’ve been visited by the gay frog of fortune",
        "kiss the bomb. (do not kiss the bomb)",
        "error 404: chill not found",
        "today’s lucky number is a mine",
        "this game is gluten free",
        "your fbi agent just cashed out",
        "nan is speedrunning")
    val LINES: Map<String, List<Pair<String, String>>> = mapOf(
        "daily_nudge" to listOf("dave" to "did the daily. ×{x}. genius behaviour, frankly", "tash" to "daily’s up. ×{x}. not saying I’m better than you but I am", "kev" to "today’s daily: ×{x}. told my manager. he did not care", "priya" to "daily done. ×{x}. your move", "nan" to "I did the daily puzzle love. ×{x}. Is that good x"),
        "daily_nudge_boom" to listOf("dave" to "the daily blew up in my face. we don’t talk about it", "tash" to "the daily is rigged. one dig. ONE", "kev" to "exploded on the daily before my coffee. great start to the day", "priya" to "daily: boom. logging off forever (back in 5)"),
        "daily_top" to listOf("dave" to "how. HOW", "tash" to "screenshot or it didn’t happen", "nan" to "Top of the class! I’m telling everyone at bingo x", "kev" to "printing this for the office fridge", "priya" to "fine. FINE. tomorrow you’re going down"),
        "daily_ok" to listOf("priya" to "×{x}. respectable. not good. respectable", "dave" to "×{x}? I’ve seen better. from Nan", "tash" to "not bad for someone who digs like that", "kev" to "×{x} is my new lucky number. I don’t have a lucky number", "nan" to "Well done love, ×{x}! Have a biscuit x"),
        "daily_boom" to listOf("dave" to "HAHAHAHA the daily got you", "nan" to "Never mind love, there’s always tomorrow x", "kev" to "the daily got me too once. solidarity", "tash" to "one go. ONE. and you spent it like that", "priya" to "see you tomorrow, champ"),
        "achievement" to listOf("tash" to "achievement unlocked: being insufferable about it", "dave" to "you get a little badge for that? cute", "nan" to "Ooh a trophy! I’ll put it on the fridge x", "kev" to "I have zero of those. zero", "priya" to "“{name}”. adding it to your obituary"),
        "hello" to listOf("dave" to "right, who’s in", "tash" to "oh here we go again", "nan" to "Don’t stay up too late love x", "priya" to "house rules: no crying at the table", "kev" to "I brought snacks. the snacks are mines", "nan" to "Is this the gambling one? Lovely x"),
        "deal_big" to listOf("dave" to "{stake} on ONE board? absolute scenes", "tash" to "oh we’re doing this are we", "kev" to "my palms are sweating and I’m not even playing", "priya" to "screenshotting this for evidence", "nan" to "Be careful love x", "tash" to "hold my earrings"),
        "boom" to listOf("dave" to "BAHAHAHA", "tash" to "that tile had a FACE on it", "kev" to "F", "priya" to "that mine had a family", "nan" to "Was that thunder love? x", "dave" to "you clicked that with your whole chest", "tash" to "down {stake}. thoughts and prayers", "kev" to "the bomb said “ok” and then did a crime", "priya" to "the googly eyes saw everything"),
        "cash_small" to listOf("tash" to "bok bok bok", "dave" to "{profit}. that’s like three meal deals", "priya" to "sensible. boring, but sensible", "nan" to "I’ll put it in the biscuit tin for you x", "kev" to "respect the bag, however small"),
        "cash_big" to listOf("dave" to "+{profit}?! drinks are on you", "priya" to "that’s generational wealth (fake)", "nan" to "Well done darling! Don’t spend it all on scratchcards x", "tash" to "buy a horse. a small one. for me", "kev" to "naming my firstborn {profit}"),
        "clear" to listOf("kev" to "CLEAN SWEEP. I need a lie down", "dave" to "not one mine. who ARE you", "priya" to "the board is naked now. look away", "nan" to "Very tidy love, like your grandad’s shed x", "tash" to "the full clear. disgusting. iconic"),
        "don_offer" to listOf("dave" to "do it. do it. do it.", "tash" to "the voices say yes. the voices are me", "nan" to "I wouldn’t love", "kev" to "I’m watching through my fingers", "priya" to "the maths says walk away. I say nothing"),
        "don_win" to listOf("dave" to "NO WAY", "tash" to "ICON. LEGEND. MOTHER.", "priya" to "the odds said no. you said yes", "kev" to "I just stood up at my desk", "nan" to "Ooh lovely x"),
        "don_lose" to listOf("dave" to "oh no. oh no no no", "tash" to "rip to your entire run", "nan" to "Never mind love. Money is just paper with ghosts in x", "kev" to "pour one out"),
        "bust" to listOf("nan" to "Come round for tea love, I’ll do you a sandwich x", "dave" to "from hero to zero", "tash" to "changing the group name to “skint”", "priya" to "respectfully: lmao", "kev" to "the goblin is going through your bins now"),
        "buy" to listOf("kev" to "ooh shiny", "priya" to "investing in yourself, love that", "dave" to "what does that even do", "nan" to "Is that one of those NFTs love? x", "tash" to "spending money to make money. classic"),
        "addon" to listOf("kev" to "ooh a little card", "tash" to "that card is doing something illegal", "priya" to "that card is giving main character", "dave" to "is that one of them lucky cards"),
        "unlock" to listOf("dave" to "new table who dis", "tash" to "moving up in the world", "kev" to "the carpet in there is sticky in a good way", "nan" to "Is that the one with the nice carpet? x"),
        "ascend" to listOf("dave" to "ASCENSION? in THIS economy?", "priya" to "more mines, more money. sounds legal", "kev" to "you’re glowing. is that radiation", "tash" to "the tables look angrier already"),
        "streak" to listOf("tash" to "{streak} in a row?? on fire", "dave" to "heater. absolute heater", "kev" to "don’t jinx it don’t jinx it", "priya" to "statistically this has to end. not my problem though"),
        "coward" to listOf("tash" to "the robot chickened out lmao", "nan" to "The robot has more sense than your grandad x"),
        "yolo" to listOf("dave" to "the robot is gambling now. we’ve created a monster", "tash" to "the robot is in its villain era"),
        "flip_win" to listOf("priya" to "coin respected you", "nan" to "I always pick heads love. Or tails. One of them x"),
        "flip_lose" to listOf("tash" to "the coin hates you specifically", "kev" to "it was always going to be the other side"),
        "shield" to listOf("priya" to "saved by the shield!", "dave" to "plot armour"),
        "fuse" to listOf("dave" to "the bomb went “pfft” lmao", "kev" to "damp squib. literally"),
        "gem" to listOf("tash" to "SHINY", "kev" to "a gem! like you", "priya" to "that’s going in the vault", "nan" to "Ooh sparkly x", "dave" to "pocket it before the goblin sees"),
        "jackpot" to listOf("dave" to "JACKPOT. I’m crying in a Wetherspoons", "tash" to "SCREAMING. CRYING. THROWING UP.", "nan" to "Ooh, that’s the fruit machine noise! x"),
        "golden" to listOf("priya" to "a golden board?? manifest it", "kev" to "everything is shiny and I’m scared"),
        "levelup" to listOf("priya" to "level up! growth!", "nan" to "Well done love, I’ve told the whole street x", "kev" to "you’re officially a {rank} now", "dave" to "{rank}? put it on your CV"),
        "spin" to listOf("tash" to "spin the wheel spin the wheel", "kev" to "the wheel is my higher power now"),
        "casino" to listOf("nan" to "My grandchild owns a CASINO x", "dave" to "I’m telling everyone I knew you before", "tash" to "free drinks forever right? right??"),
        "odd_co" to listOf("kev" to "is that the carbon monoxide alarm", "nan" to "That’s the CO one love, it wants a new battery x", "tash" to "that chirp is going to live in my head rent free", "dave" to "it’ll do that once a minute for three weeks. it’s tradition", "priya" to "we are all being haunted by one small battery"),
        "odd_microwave" to listOf("tash" to "who’s microwaving fish at this hour", "dave" to "your pizza’s done"),
        "odd_buzz" to listOf("priya" to "your phone’s going", "kev" to "is that the bank calling"),
        "odd_kettle" to listOf("nan" to "Ooh put one on for me love x", "priya" to "tea break?? mid-game??"),
        "odd_doorbell" to listOf("dave" to "don’t answer it. it’s the bailiffs", "tash" to "expecting someone? ;)"),
        "odd_fart" to listOf("tash" to "who did that", "kev" to "not me", "dave" to "better out than in"),
        "odd_duck" to listOf("priya" to "why is there a duck", "dave" to "quack"),
        "odd_creak" to listOf("dave" to "did anyone else hear that door", "nan" to "Is somebody there? x"),
        "odd_meow" to listOf("nan" to "Has someone fed the cat? x", "tash" to "KITTY"))
    val DAILY_EPOCH = listOf(2026, 10, 6)
    const val DAILY_TABLE = "alley"
    const val DAILY_LIMIT = 100.0
    const val DAILY_GEMS = 3
    const val DAILY_PRIZE = 0.3
    const val DAILY_SEED = "sweepstakes-daily-"
    const val DAILY_CHAT_SEED = "sweepstakes-chat-"
    val DAILY_STYLES = listOf(Style("nan", 0.0, 1.2, 2.6), Style("kev", 0.2, 1.1, 3.5), Style("tash", 0.3, 1.8, 8.0), Style("priya", 0.25, 2.5, 10.0), Style("dave", 0.45, 3.0, 18.0))
    val GOLDEN_BOARDS = listOf(
        GoldenBoard("2026-10-06", 1, "000001000000000000100001000000011100100000110000101100100000000000001000000001110", "111110000111110000011110000011100000011100000000000000000000000000000000000000000", listOf(25 to 1.5, 46 to 1.5, 58 to 1.2), listOf("nan" to 2.01, "kev" to 1.18, "tash" to 3.9, "priya" to 9.49, "dave" to 12.02)),
        GoldenBoard("2026-12-25", 81, "000000001100011101001000000000000000000010001101100000000100000000010001011000000", "000000000000000000000001110000001110000001110000001110000001110000001110000001110", listOf(21 to 1.5, 56 to 1.2, 66 to 1.2), listOf("nan" to 1.89, "kev" to 2.78, "tash" to 5.32, "priya" to 0.0, "dave" to 0.0)),
        GoldenBoard("2027-02-28", 146, "000000101000010110001100010000000010000000000000000011000000000010000000001010111", "111100000111100000110011100111111100111111100111111100111111100001111100000000000", listOf(14 to 1.5, 43 to 1.2, 71 to 1.5), listOf("nan" to 1.56, "kev" to 1.69, "tash" to 1.98, "priya" to 8.76, "dave" to 0.0)),
        GoldenBoard("2030-01-01", 1184, "001100011010110000000000000000000010000000000110010001000000101010000001001000000", "000000000000000000111111100111111100111111100000000000000000000000000000000000000", listOf(50 to 2.0, 51 to 1.2, 52 to 1.5), listOf("nan" to 1.51, "kev" to 1.24, "tash" to 2.06, "priya" to 2.51, "dave" to 0.0)))
    val GOLDEN_RUNS = listOf(
        GoldenRun("2026-10-06", listOf("safe", "safe", "safe", "gem", "safe", "safe", "safe", "safe", "safe", "gem", "safe", "safe"), 32, 1.9227272727272724, "cash"),
        GoldenRun("2026-12-25", listOf("safe", "gem", "safe", "safe", "safe", "safe", "safe", "r2", "r2", "safe", "safe", "safe"), 38, 4.087360365073582, "cash"),
        GoldenRun("2027-02-28", listOf("safe", "safe", "safe", "safe", "safe", "r2", "boom"), 52, 0.0, "boom"),
        GoldenRun("2030-01-01", listOf("safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe", "safe"), 33, 1.069767441860465, "cash"))
}
