// Ambient group-chat conversations.

// Little conversations the group chat has on its own, unprompted. Nobody asked for them.
export const THREADS = [
  [['dave', 'my marrow is 4kg. FOUR'], ['priya', 'is that a lot'], ['dave', 'it is MASSIVE priya'], ['nan', 'Lovely marrow Dave. I’ll make chutney x']],
  [['kev', 'put my own song on the jukebox at the Red Lion'], ['tash', 'Insert Coin?'], ['kev', 'royalties incoming'], ['tash', 'it’s on free play kev']],
  [['priya', 'did anyone do Spot the Mine in the paper'], ['dave', 'got it in one'], ['priya', 'you did not'], ['dave', 'I got it in four']],
  [['nan', 'I’ve saved you the puzzle page out of the paper love. And the coupons x']],
  [['tash', 'who keeps putting Nan’s Wireless on the jukebox'], ['nan', 'That’s me love. It’s our song x'], ['tash', 'ok it is now']],
  [['dave', 'karaoke tonight. I’m doing Last Orders'], ['priya', 'you do Last Orders every week'], ['dave', 'and every week I get closer to the words']],
  [['kev', 'bought five lines on the Sweepstake'], ['priya', 'and?'], ['kev', 'one number. ONE'], ['nan', 'Better luck next time love. I’ll put the kettle on x']],
  [['nan', 'Saved you some seeds from my garden love. Carrots and a few radishes. Plant them in nice straight rows x']],
  [['priya', 'who wants conkers. mine’s a sixer'], ['dave', 'soaked in vinegar?'], ['priya', 'it’s been marinating'], ['tash', 'that’s a pickled egg priya']],
  [['dave', 'fete’s on saturday. I’m defending my Splat the Rat title'], ['kev', 'there isn’t a title'], ['dave', 'there is now']],
  [['nan', 'I’m doing a roast on Sunday love. Bring a friend if you like x'], ['dave', 'can I be the friend'], ['nan', 'Of course Dave. There’s always enough to go round x']],
  [['tash', 'landlord’s chalked a lock-in on the board again'], ['kev', 'I’ve been in since Tuesday'], ['tash', 'kev go home']],
  [['kev', 'had a kebab at 3am. best decision I’ve ever made'], ['priya', 'it’s 3.04am kev'], ['kev', 'having another']],
  [['priya', 'the milkman came round today'], ['dave', 'there hasn’t been a milkman since 1994'], ['priya', 'then who left the gold tops'], ['dave', '…']],
  [['kev', 'anyone know how to get a seagull out of a car'], ['dave', 'why is there a seagull in your car'], ['kev', 'that is not what I asked']],
  [['nan', 'Made too much shepherd’s pie again. Come round tomorrow love, I’ll save you the crispy bit x']],
  [['tash', 'my sourdough starter just said my name'], ['priya', 'what did it sound like'], ['tash', 'yeasty']],
  [['dave', 'hear me out. cargo shorts but for your arms']],
  [['priya', 'found a tooth in my coat pocket. not mine. not asking.']],
  [['kev', 'the yoghurt in the office fridge is from 2021. it has a name now. it’s Gary']],
  [['nan', 'I’ve joined a gang love. It’s the knitting circle but we’re very dangerous x']],
  [['tash', 'just saw two pigeons holding hands outside Tesco'], ['dave', 'love wins'], ['kev', 'pigeons don’t have hands'], ['tash', 'they made it work']],
  [['dave', 'my landlord texted “u up” about the boiler']],
  [['priya', 'a group of flamingos is called a flamboyance. that’s it. that’s the message']],
  [['kev', 'accidentally replied-all “love you” to the whole company'], ['tash', 'and?'], ['kev', 'HR said it back']],
  [['nan', 'What does “slay” mean? Your cousin said it about my trifle x'], ['tash', 'it means your trifle is iconic nan'], ['nan', 'Oh lovely. It is x']],
  [['dave', 'my mum just asked what minesweeper is. she’s on Ascension II now']],
  [['priya', 'alexa added condoms to my shopping cart again'], ['priya', 'I don’t own an alexa'], ['kev', 'who is in your house priya']],
  [['tash', 'my gaydar just pinged the toaster'], ['dave', 'the toaster is bi. everyone knows that']],
  [['kev', 'the vending machine at work gave me two KitKats. I think it likes me']],
  [['dave', 'anyone want a slightly used trampoline. it’s on my roof. don’t ask how']],
  [['nan', 'Don’t forget to drink some water love. And eat something green x'], ['kev', 'does a mint count'], ['nan', 'No Kevin x']],
  [['priya', 'I’ve started talking to the goblin. he gets me']],
  [['kev', 'sorry if I’m quiet. at goat yoga. a goat is on me. I live here now']],
  [['tash', 'I have never seen a baby pigeon. where are they keeping them']],
  [['dave', 'the bomb winked at me. I saw it. I’m not well']],
  [['nan', 'I’ve knitted everyone in the chat a scarf for winter. Dave’s is extra long x'], ['dave', 'nan I’m six foot four'], ['nan', 'That’s why love x']],
  [['priya', 'today’s affirmation: I am a mine and nobody can stop me']],
  [['kev', 'is anyone else’s smoke alarm chirping or is it just my soul']],
  [['tash', 'new life goal: be as confident as a pigeon walking into Greggs']],
  [['dave', 'me and the lads are starting a band. we’re called Unrevealed Tile'], ['tash', 'first album?'], ['dave', '“Cashed Out Too Early”']],
  [['nan', 'I’ve put a fiver in your birthday card already. Don’t tell the others x'], ['tash', 'nan we can all see this'], ['nan', 'Oh. Well there’s a fiver for everyone then x']],
  [['kev', 'just realised I left my crocs in sport mode at a funeral']],
  [['tash', 'is it gay to have a favourite tile? asking for a 7']],
  [['dave', 'opened a fortune cookie and it just said “cash out”'], ['kev', 'did you'], ['dave', 'no']],
  [['nan', 'The cat brought me a whole sausage roll x'], ['tash', 'where did it get a sausage roll'], ['nan', 'Don’t ask questions love x']],
  [['priya', 'my horoscope says “avoid mines”. bit specific'], ['kev', 'what’s your sign'], ['priya', 'flag']],
  [['kev', 'my smart fridge just asked if I’m ok']],
  [['tash', 'pride month is twelve months long if you’re brave enough']],
  // around the house, and the state of things
  [['nan', 'Lit a candle at church for your next board love. And one at the mosque, and one at the synagogue. Covering all the bases x'], ['dave', 'nan’s hedging her bets'],
    ['tash', 'nan is the only one in this chat who understands risk management']],
  [['dave', 'a priest, a rabbi and an imam walk into a casino'], ['tash', 'and?'], ['dave', 'they split a meal deal, play one hand of bingo and leave by ten. sensible people'],
    ['kev', 'that’s not a joke, that’s a nice evening']],
  [['kev', 'is gambling a sin'], ['nan', 'Not if you win love x'], ['priya', 'nan is running a very relaxed church']],
  [['nan', 'The prayer group is praying for your stake love. Margaret’s doing a double shift x']],
  [['kev', 'if the mines started a political party would you vote for them'], ['tash', 'they’d win. they always win'], ['dave', 'manifesto: boom'], ['priya', 'still more coherent than the actual lot']],
  [['tash', 'the bomb is standing for parliament'], ['kev', 'slogan?'], ['tash', '“vote boom, get boom”'], ['dave', 'first honest candidate in years']],
  [['priya', 'emailed my MP about the Abyss table being rigged'], ['dave', 'and?'], ['priya', '“thank you for your feedback.” classic']],
  [['kev', 'an MP once claimed a duck house on expenses'], ['tash', 'and I can’t even claim a biro'], ['dave', 'the ducks are the only real winners in British politics']],
  [['nan', 'Saw a lovely sunset tonight and thought of you all x'], ['priya', 'nan that’s the nicest thing anyone’s ever said in this chat'], ['nan', 'Well you’re all lovely x']],
  [['priya', 'do I have to pay tax on fake coins'], ['dave', 'don’t say that too loud'], ['kev', 'the taxman is reading this chat'], ['nan', 'Hello Mr Taxman, my grandchild is a lovely person x']],
  [['dave', 'the ducks at the park have started charging for bread'], ['tash', 'good for them'], ['kev', 'late stage capitalism has reached the pond']],
  [['tash', 'there’s a kitten in the casino now'], ['kev', 'who let a kitten in'], ['priya', 'the kitten owns 40% of the casino'], ['dave', 'all hail the kitten']],
  [['kev', 'the council finally fixed the pothole outside mine'], ['dave', 'and?'], ['kev', 'they put a cone in it']],
  [['priya', 'the kitten keeps sitting on the 8'], ['tash', 'it knows']],
  [['kev', 'just found a fiver in last winter’s coat'], ['dave', 'best feeling in the world'], ['nan', 'I put that there love. Every coat you own has one x'], ['tash', 'NAN']],
  [['nan', 'Made a lemon drizzle. There’s a slice with your name on it, I iced it on x'], ['dave', 'is there one with my name on'], ['nan', 'There’s one for everyone love x']],
  [['nan', 'Thinking of you all today. Don’t forget to eat something hot x'], ['priya', 'nan I had a pot noodle'], ['nan', 'That counts love x']],
  [['priya', 'went to a car boot sale and bought my own bike back'], ['dave', 'how much'], ['priya', 'a tenner. bargain, honestly']],
  [['dave', 'my claw machine strategy: pray'], ['kev', 'mine is crying'], ['tash', 'mine is getting someone else to do it']],
  [['tash', 'someone at the pub quiz put “the goblin” for every answer'], ['kev', 'and?'], ['tash', 'they came third']],
  [['kev', 'KEVCOIN update: we are rebranding to KEV'], ['priya', 'it was already called KEV'], ['kev', 'and now it’s official']],
  [['priya', 'the pigeons outside my window have started queueing'], ['dave', 'for what'], ['priya', 'nobody knows. they just queue. very British']],
  [['dave', 'the dog next door just winked at me'], ['tash', 'Biscuit winks at everyone'], ['dave', 'I thought we had something']],
  [['kev', 'my horoscope said “beware of tall strangers”'], ['dave', 'I’m six foot four'], ['kev', 'I know, dave. I know']],
];
// The ruder conversations (only with "Rude chat" on).
export const RUDE_THREADS = [
  [['dave', 'lent Kev a tenner in 2019'], ['kev', 'and I’ll pay it back when I’m good and ready'], ['dave', 'it’s been seven years, you tight git']],
  [['tash', 'my ex just liked my post from 2017'], ['priya', 'block the absolute weasel'], ['nan', 'Do you want me to have a word love? I know people x']],
  [['kev', 'just walked into a glass door at work'], ['dave', 'in front of people?'], ['kev', 'in front of the whole bloody board meeting']],
  [['dave', 'pissed again'], ['priya', 'it’s 2pm'], ['dave', 'and?']],
  [['kev', 'the bloody printer’s jammed again'], ['dave', 'kick it'], ['kev', 'I kicked it. it printed my P45']],
  [['tash', 'some prat in a massive car just parked across three spaces'], ['dave', 'they always do'], ['kev', 'leave a passive aggressive note. the British way']],
  [['priya', 'my landlord wants a rent rise because of the mould'], ['dave', 'premium mould'], ['tash', 'artisanal damp']],
  [['kev', 'is it bad that I gamble to cope with gambling'], ['dave', 'mate'], ['tash', 'MATE']],
];
