// Ambient group-chat conversations.

// Little conversations the group chat has on its own, unprompted. Nobody asked for them.
export const THREADS = [
  [['kev', 'anyone know how to get a seagull out of a car'], ['dave', 'why is there a seagull in your car'], ['kev', 'that is not what I asked']],
  [['nan', 'Who is Bluetooth and why does he want to pair with me x']],
  [['tash', 'my sourdough starter just said my name'], ['priya', 'what did it sound like'], ['tash', 'yeasty']],
  [['dave', 'hear me out. cargo shorts but for your arms']],
  [['priya', 'found a tooth in my coat pocket. not mine. not asking.']],
  [['kev', 'the yoghurt in the office fridge is from 2021. it has a name now. it’s Gary']],
  [['nan', 'I’ve joined a gang love. It’s the knitting circle but we’re very dangerous x']],
  [['tash', 'just saw two pigeons holding hands outside Tesco'], ['dave', 'love wins'], ['kev', 'pigeons don’t have hands'], ['tash', 'they made it work']],
  [['dave', 'my landlord texted “u up” about the boiler']],
  [['priya', 'a group of flamingos is called a flamboyance. that’s it. that’s the message']],
  [['kev', 'accidentally replied-all “love you” to the whole company'], ['tash', 'and?'], ['kev', 'HR said it back']],
  [['nan', 'What does “slay” mean? Your cousin said it about my trifle x'], ['tash', 'it means your trifle is iconic nan'], ['nan', 'Oh lovely. It is x']],
  [['dave', 'my mum just asked what minesweeper is. she’s on Ascension II now']],
  [['priya', 'alexa added condoms to my shopping cart again'], ['priya', 'I don’t own an alexa'], ['kev', 'who is in your house priya']],
  [['tash', 'my gaydar just pinged the toaster'], ['dave', 'the toaster is bi. everyone knows that']],
  [['kev', 'the vending machine at work gave me two KitKats. I think it likes me']],
  [['dave', 'anyone want a slightly used trampoline. it’s on my roof. don’t ask how']],
  [['nan', 'Can someone tell the man in my phone to stop talking x'], ['priya', 'nan that’s a podcast'], ['nan', 'Well he’s very rude x']],
  [['priya', 'I’ve started talking to the goblin. he gets me']],
  [['kev', 'sorry if I’m quiet. at goat yoga. a goat is on me. I live here now']],
  [['tash', 'I have never seen a baby pigeon. where are they keeping them']],
  [['dave', 'the bomb winked at me. I saw it. I’m not well']],
  [['nan', 'Your grandad played minesweeper. Never cashed out once. He’s fine, he lives in Margate now x']],
  [['priya', 'today’s affirmation: I am a mine and nobody can stop me']],
  [['kev', 'is anyone else’s smoke alarm chirping or is it just my soul']],
  [['tash', 'new life goal: be as confident as a pigeon walking into Greggs']],
  [['dave', 'me and the lads are starting a band. we’re called Unrevealed Tile'], ['tash', 'first album?'], ['dave', '“Cashed Out Too Early”']],
  [['nan', 'I put a bet on the horses love. I don’t know which horses. I just shouted x']],
  [['kev', 'just realised I left my crocs in sport mode at a funeral']],
  [['tash', 'is it gay to have a favourite tile? asking for a 7']],
  [['dave', 'opened a fortune cookie and it just said “cash out”'], ['kev', 'did you'], ['dave', 'no']],
  [['nan', 'The cat brought me a whole sausage roll x'], ['tash', 'where did it get a sausage roll'], ['nan', 'Don’t ask questions love x']],
  [['priya', 'my horoscope says “avoid mines”. bit specific'], ['kev', 'what’s your sign'], ['priya', 'flag']],
  [['kev', 'my smart fridge just asked if I’m ok']],
  [['tash', 'pride month is twelve months long if you’re brave enough']],
  // around the house, and the state of things
  [['nan', 'Lit a candle at church for your next board love. And one at the mosque, and one at the synagogue. Covering all the bases x'], ['dave', 'nan’s hedging her bets'],
    ['tash', 'nan is the only one in this chat who understands risk management']],
  [['dave', 'a priest, a rabbi and an imam walk into a casino'], ['tash', 'and?'], ['dave', 'they split a meal deal, play one hand of bingo and leave by ten. sensible people'],
    ['kev', 'that’s not a joke, that’s a nice evening']],
  [['kev', 'is gambling a sin'], ['nan', 'Not if you win love x'], ['priya', 'nan is running a very relaxed church']],
  [['nan', 'The prayer group is praying for your stake love. Margaret says it’s a lost cause x']],
  [['kev', 'if the mines started a political party would you vote for them'], ['tash', 'they’d win. they always win'], ['dave', 'manifesto: boom'], ['priya', 'still more coherent than the actual lot']],
  [['tash', 'the bomb is standing for parliament'], ['kev', 'slogan?'], ['tash', '“vote boom, get boom”'], ['dave', 'first honest candidate in years']],
  [['priya', 'emailed my MP about the Abyss table being rigged'], ['dave', 'and?'], ['priya', '“thank you for your feedback.” classic']],
  [['kev', 'an MP once claimed a duck house on expenses'], ['tash', 'and I can’t even claim a biro'], ['dave', 'the ducks are the only real winners in British politics']],
  [['nan', 'I voted for the one with the nicest tie love. That’s democracy x'], ['priya', 'honestly as good a system as any']],
  [['priya', 'do I have to pay tax on fake coins'], ['dave', 'don’t say that too loud'], ['kev', 'the taxman is reading this chat'], ['nan', 'Hello Mr Taxman, my grandchild is a lovely person x']],
  [['dave', 'the ducks at the park have started charging for bread'], ['tash', 'good for them'], ['kev', 'late stage capitalism has reached the pond']],
  [['tash', 'there’s a kitten in the casino now'], ['kev', 'who let a kitten in'], ['priya', 'the kitten owns 40% of the casino'], ['dave', 'all hail the kitten']],
  [['kev', 'the council finally fixed the pothole outside mine'], ['dave', 'and?'], ['kev', 'they put a cone in it']],
  [['priya', 'the kitten keeps sitting on the 8'], ['tash', 'it knows']],
];
// The ruder conversations (only with "Rude chat" on).
export const RUDE_THREADS = [
  [['dave', 'lent Kev a tenner in 2019'], ['kev', 'and I’ll pay it back when I’m good and ready'], ['dave', 'it’s been seven years, you tight git']],
  [['tash', 'my ex just liked my post from 2017'], ['priya', 'block the absolute weasel'], ['nan', 'Do you want me to have a word love? I know people x']],
  [['kev', 'just walked into a glass door at work'], ['dave', 'in front of people?'], ['kev', 'in front of the whole bloody board meeting']],
  [['dave', 'pissed again'], ['priya', 'it’s 2pm'], ['dave', 'and?']],
  [['nan', 'Your grandad’s been at the sherry. He’s challenged the cat to a fight x'], ['tash', 'who’s winning'], ['nan', 'The cat love x']],
  [['tash', 'some prat in a massive car just parked across three spaces'], ['dave', 'they always do'], ['kev', 'leave a passive aggressive note. the British way']],
  [['priya', 'my landlord wants a rent rise because of the mould'], ['dave', 'premium mould'], ['tash', 'artisanal damp']],
  [['kev', 'is it bad that I gamble to cope with gambling'], ['dave', 'mate'], ['tash', 'MATE']],
];
