// Who is in the group chat, and the lines they say when things happen.

export const FRIENDS = {
  dave:  { name: 'Big Dave',      col: '#009dff', bg: '#ffb38a', extra: '<path d="M5 15 Q20 0 35 15 Z" fill="#009dff" stroke="#141b1d" stroke-width="2.5"/><path d="M31 14 h8" stroke="#141b1d" stroke-width="3"/>', mouth: 'M14 27 q6 5 12 0' },
  tash:  { name: 'Tash',          col: '#fe5f55', bg: '#d9925f', extra: '<circle cx="7" cy="8" r="6" fill="#fe5f55" stroke="#141b1d" stroke-width="2"/><circle cx="33" cy="8" r="6" fill="#fe5f55" stroke="#141b1d" stroke-width="2"/>', mouth: 'M15 27 q5 3 10 0' },
  kev:   { name: 'Kev from work', col: '#3fc18a', bg: '#ffd7b5', extra: '<g fill="none" stroke="#141b1d" stroke-width="2"><circle cx="14.5" cy="20" r="5"/><circle cx="25.5" cy="20" r="5"/></g>', mouth: 'M15 28 h10' },
  nan:   { name: 'Nan',           col: '#a275f0', bg: '#ffe3d1', extra: '<g fill="#c9d6da" stroke="#141b1d" stroke-width="2"><circle cx="9" cy="10" r="5.5"/><circle cx="20" cy="6" r="5.5"/><circle cx="31" cy="10" r="5.5"/></g>', mouth: 'M14 26 q6 6 12 0' },
  priya: { name: 'Priya',         col: '#ffd23f', bg: '#a8714a', extra: '<path d="M4 14 Q20 3 36 14" fill="none" stroke="#ffd23f" stroke-width="4.5"/>', mouth: 'M15 27 q5 4 10 0' },
};
export const LINES = {
  // the Daily Challenge ({x} is their multiplier; Nan never blows up, she plays it safe)
  daily_nudge: [['dave', 'did the daily. ×{x}. genius behaviour, frankly'], ['tash', 'daily’s up. ×{x}. not saying I’m better than you but I am'],
    ['kev', 'today’s daily: ×{x}. told my manager. he did not care'], ['priya', 'daily done. ×{x}. your move'], ['nan', 'I did the daily puzzle love. ×{x}. Is that good x']],
  daily_nudge_boom: [['dave', 'the daily blew up in my face. we don’t talk about it'], ['tash', 'the daily is rigged. one dig. ONE'],
    ['kev', 'exploded on the daily before my coffee. great start to the day'], ['priya', 'daily: boom. logging off forever (back in 5)']],
  daily_top: [['dave', 'how. HOW'], ['tash', 'screenshot or it didn’t happen'], ['nan', 'Top of the class! I’m telling everyone at bingo x'],
    ['kev', 'printing this for the office fridge'], ['priya', 'fine. FINE. tomorrow you’re going down']],
  daily_ok: [['priya', '×{x}. respectable. not good. respectable'], ['dave', '×{x}? I’ve seen better. from Nan'], ['tash', 'not bad for someone who digs like that'],
    ['kev', '×{x} is my new lucky number. I don’t have a lucky number'], ['nan', 'Well done love, ×{x}! Have a biscuit x']],
  daily_boom: [['dave', 'HAHAHAHA the daily got you'], ['nan', 'Never mind love, there’s always tomorrow x'], ['kev', 'the daily got me too once. solidarity'],
    ['tash', 'one go. ONE. and you spent it like that'], ['priya', 'see you tomorrow, champ']],
  achievement: [['tash', 'achievement unlocked: being insufferable about it'], ['dave', 'you get a little badge for that? cute'],
    ['nan', 'Ooh a trophy! I’ll put it on the fridge x'], ['kev', 'I have zero of those. zero'], ['priya', '“{name}”. adding it to your obituary']],
  hello:    [['dave', 'right, who’s in'], ['tash', 'oh here we go again'], ['nan', 'Don’t stay up too late love x'], ['priya', 'house rules: no crying at the table'], ['kev', 'I brought snacks. the snacks are mines'], ['nan', 'Is this the gambling one? Lovely x']],
  deal_big: [['dave', '{stake} on ONE board? absolute scenes'], ['tash', 'oh we’re doing this are we'], ['kev', 'my palms are sweating and I’m not even playing'], ['priya', 'screenshotting this for evidence'], ['nan', 'Be careful love x'], ['tash', 'hold my earrings']],
  boom:     [['dave', 'BAHAHAHA'], ['tash', 'that tile had a FACE on it'], ['kev', 'F'], ['priya', 'that mine had a family'], ['nan', 'Was that thunder love? x'], ['dave', 'you clicked that with your whole chest'], ['tash', 'down {stake}. thoughts and prayers'], ['kev', 'the bomb said “ok” and then did a crime'], ['priya', 'the googly eyes saw everything']],
  cash_small: [['tash', 'bok bok bok'], ['dave', '{profit}. that’s like three meal deals'], ['priya', 'sensible. boring, but sensible'], ['nan', 'I’ll put it in the biscuit tin for you x'], ['kev', 'respect the bag, however small']],
  cash_big: [['dave', '+{profit}?! drinks are on you'], ['priya', 'that’s generational wealth (fake)'], ['nan', 'Well done darling! Don’t spend it all on scratchcards x'], ['tash', 'buy a horse. a small one. for me'], ['kev', 'naming my firstborn {profit}']],
  clear:    [['kev', 'CLEAN SWEEP. I need a lie down'], ['dave', 'not one mine. who ARE you'], ['priya', 'the board is naked now. look away'], ['nan', 'Very tidy love, like your grandad’s shed x'], ['tash', 'the full clear. disgusting. iconic']],
  don_offer:[['dave', 'do it. do it. do it.'], ['tash', 'the voices say yes. the voices are me'], ['nan', 'I wouldn’t love'], ['kev', 'I’m watching through my fingers'], ['priya', 'the maths says walk away. I say nothing']],
  don_win:  [['dave', 'NO WAY'], ['tash', 'ICON. LEGEND. MOTHER.'], ['priya', 'the odds said no. you said yes'], ['kev', 'I just stood up at my desk'], ['nan', 'Ooh lovely x']],
  don_lose: [['dave', 'oh no. oh no no no'], ['tash', 'rip to your entire run'], ['nan', 'Never mind love. Money is just paper with ghosts in x'], ['kev', 'pour one out']],
  bust:     [['nan', 'Come round for tea love, I’ll do you a sandwich x'], ['dave', 'from hero to zero'], ['tash', 'changing the group name to “skint”'], ['priya', 'respectfully: lmao'], ['kev', 'the goblin is going through your bins now']],
  buy:      [['kev', 'ooh shiny'], ['priya', 'investing in yourself, love that'], ['dave', 'what does that even do'], ['nan', 'Is that one of those NFTs love? x'], ['tash', 'spending money to make money. classic']],
  addon:    [['kev', 'ooh a little card'], ['tash', 'that card is doing something illegal'], ['priya', 'that card is giving main character'], ['dave', 'is that one of them lucky cards']],
  unlock:   [['dave', 'new table who dis'], ['tash', 'moving up in the world'], ['kev', 'the carpet in there is sticky in a good way'], ['nan', 'Is that the one with the nice carpet? x']],
  ascend:   [['dave', 'ASCENSION? in THIS economy?'], ['priya', 'more mines, more money. sounds legal'], ['kev', 'you’re glowing. is that radiation'], ['tash', 'the tables look angrier already']],
  streak:   [['tash', '{streak} in a row?? on fire'], ['dave', 'heater. absolute heater'], ['kev', 'don’t jinx it don’t jinx it'], ['priya', 'statistically this has to end. not my problem though']],
  coward:   [['tash', 'the robot chickened out lmao'], ['nan', 'The robot has more sense than your grandad x']],
  yolo:     [['dave', 'the robot is gambling now. we’ve created a monster'], ['tash', 'the robot is in its villain era']],
  flip_win: [['priya', 'coin respected you'], ['nan', 'I always pick heads love. Or tails. One of them x']],
  flip_lose:[['tash', 'the coin hates you specifically'], ['kev', 'it was always going to be the other side']],
  shield:   [['priya', 'saved by the shield!'], ['dave', 'plot armour']],
  fuse:     [['dave', 'the bomb went “pfft” lmao'], ['kev', 'damp squib. literally']],
  gem:      [['tash', 'SHINY'], ['kev', 'a gem! like you'], ['priya', 'that’s going in the vault'], ['nan', 'Ooh sparkly x'], ['dave', 'pocket it before the goblin sees']],
  jackpot:  [['dave', 'JACKPOT. I’m crying in a Wetherspoons'], ['tash', 'SCREAMING. CRYING. THROWING UP.'], ['nan', 'Ooh, that’s the fruit machine noise! x']],
  golden:   [['priya', 'a golden board?? manifest it'], ['kev', 'everything is shiny and I’m scared']],
  levelup:  [['priya', 'level up! growth!'], ['nan', 'Well done love, I’ve told the whole street x'], ['kev', 'you’re officially a {rank} now'], ['dave', '{rank}? put it on your CV']],
  spin:     [['tash', 'spin the wheel spin the wheel'], ['kev', 'the wheel is my higher power now']],
  casino:   [['nan', 'My grandchild owns a CASINO x'], ['dave', 'I’m telling everyone I knew you before'], ['tash', 'free drinks forever right? right??']],
  odd_co:        [['kev', 'is that the carbon monoxide alarm'], ['nan', 'That’s the CO one love, it wants a new battery x'], ['tash', 'that chirp is going to live in my head rent free'], ['dave', 'it’ll do that once a minute for three weeks. it’s tradition'], ['priya', 'we are all being haunted by one small battery']],
  odd_microwave: [['tash', 'who’s microwaving fish at this hour'], ['dave', 'your pizza’s done']],
  odd_buzz:      [['priya', 'your phone’s going'], ['kev', 'is that the bank calling']],
  odd_kettle:    [['nan', 'Ooh put one on for me love x'], ['priya', 'tea break?? mid-game??']],
  odd_doorbell:  [['dave', 'don’t answer it. it’s the bailiffs'], ['tash', 'expecting someone? ;)']],
  odd_fart:      [['tash', 'who did that'], ['kev', 'not me'], ['dave', 'better out than in']],
  odd_duck:      [['priya', 'why is there a duck'], ['dave', 'quack']],
  odd_creak:     [['dave', 'did anyone else hear that door'], ['nan', 'Is somebody there? x']],
  odd_meow:      [['nan', 'Has someone fed the cat? x'], ['tash', 'KITTY']],
};
export const CHANCE = { boom: .7, cash_small: .3, cash_big: .9, clear: .9, deal_big: .8, buy: .5, addon: .6, coward: .25, yolo: .3, streak: .8, fuse: .8, gem: .35, golden: .7, spin: .5 };
// Double or Nothing asks this before each rung of the ladder.
export const SURE = ['Are you sure?', 'Are you SURE sure?', 'Mate. Are you actually sure?', 'This is where sensible people stop.', 'Nan is crying. Are you sure?'];
