// Who is in the group chat, and the lines they say when things happen.

export const FRIENDS = {
  dave:  { name: 'Big Dave',      col: '#009dff', bg: '#ffb38a', extra: '<path d="M5 15 Q20 0 35 15 Z" fill="#009dff" stroke="#141b1d" stroke-width="2.5"/><path d="M31 14 h8" stroke="#141b1d" stroke-width="3"/>', mouth: 'M14 27 q6 5 12 0' },
  tash:  { name: 'Tash',          col: '#fe5f55', bg: '#d9925f', extra: '<circle cx="7" cy="8" r="6" fill="#fe5f55" stroke="#141b1d" stroke-width="2"/><circle cx="33" cy="8" r="6" fill="#fe5f55" stroke="#141b1d" stroke-width="2"/>', mouth: 'M15 27 q5 3 10 0' },
  kev:   { name: 'Kev from work', col: '#3fc18a', bg: '#ffd7b5', extra: '<g fill="none" stroke="#141b1d" stroke-width="2"><circle cx="14.5" cy="20" r="5"/><circle cx="25.5" cy="20" r="5"/></g>', mouth: 'M15 28 h10' },
  nan:   { name: 'Nan',           col: '#a275f0', bg: '#ffe3d1', extra: '<g fill="#c9d6da" stroke="#141b1d" stroke-width="2"><circle cx="9" cy="10" r="5.5"/><circle cx="20" cy="6" r="5.5"/><circle cx="31" cy="10" r="5.5"/></g>', mouth: 'M14 26 q6 6 12 0' },
  priya: { name: 'Priya',         col: '#ffd23f', bg: '#a8714a', extra: '<path d="M4 14 Q20 3 36 14" fill="none" stroke="#ffd23f" stroke-width="4.5"/>', mouth: 'M15 27 q5 4 10 0' },
};
export const LINES = {
  // the Daily Challenge ({x} is their multiplier; Nan never blows up, she plays it safe)
  daily_nudge: [['dave', 'did the daily. ×{x}. genius behaviour, frankly'], ['tash', 'daily’s up. ×{x}. not saying I’m better than you but I am'],
    ['kev', 'today’s daily: ×{x}. told my manager. he did not care'], ['priya', 'daily done. ×{x}. your move'], ['nan', 'I did the daily puzzle love. ×{x}. Is that good x']],
  daily_nudge_boom: [['dave', 'the daily blew up in my face. we don’t talk about it'], ['tash', 'the daily is rigged. one dig. ONE'],
    ['kev', 'exploded on the daily before my coffee. great start to the day'], ['priya', 'daily: boom. logging off forever (back in 5)']],
  daily_top: [['dave', 'how. HOW'], ['tash', 'screenshot or it didn’t happen'], ['nan', 'Top of the class! I’m telling everyone at bingo x'],
    ['kev', 'printing this for the office fridge'], ['priya', 'fine. FINE. tomorrow you’re going down']],
  daily_ok: [['priya', '×{x}. respectable. not good. respectable'], ['dave', '×{x}? I’ve seen better. from Nan'], ['tash', 'not bad for someone who digs like that'],
    ['kev', '×{x} is my new lucky number. I don’t have a lucky number'], ['nan', 'Well done love, ×{x}! Have a biscuit x']],
  daily_boom: [['dave', 'HAHAHAHA the daily got you'], ['nan', 'Never mind love, there’s always tomorrow x'], ['kev', 'the daily got me too once. solidarity'],
    ['tash', 'one go. ONE. and you spent it like that'], ['priya', 'see you tomorrow, champ']],
  achievement: [['tash', 'achievement unlocked: being insufferable about it'], ['dave', 'you get a little badge for that? cute'],
    ['nan', 'Ooh a trophy! I’ll put it on the fridge x'], ['kev', 'I have zero of those. zero'], ['priya', '“{name}”. adding it to your obituary']],
  hello:    [['dave', 'right, who’s in'], ['tash', 'oh here we go again'], ['nan', 'Don’t stay up too late love x'], ['priya', 'house rules: no crying at the table'], ['kev', 'I brought snacks. the snacks are mines'], ['nan', 'Is this the gambling one? Lovely x']],
  deal_big: [['dave', '{stake} on ONE board? absolute scenes'], ['tash', 'oh we’re doing this are we'], ['kev', 'my palms are sweating and I’m not even playing'], ['priya', 'screenshotting this for evidence'], ['nan', 'Be careful love x'], ['tash', 'hold my earrings']],
  boom:     [['dave', 'BAHAHAHA'], ['tash', 'that tile had a FACE on it'], ['kev', 'F'], ['priya', 'that mine had a family'], ['nan', 'Was that thunder love? x'], ['dave', 'you clicked that with your whole chest'], ['tash', 'down {stake}. thoughts and prayers'], ['kev', 'the bomb said “ok” and then did a crime'], ['priya', 'the googly eyes saw everything']],
  cash_small: [['tash', 'bok bok bok'], ['dave', '{profit}. that’s like three meal deals'], ['priya', 'sensible. boring, but sensible'], ['nan', 'I’ll put it in the biscuit tin for you x'], ['kev', 'respect the bag, however small']],
  cash_big: [['dave', '+{profit}?! drinks are on you'], ['priya', 'that’s generational wealth (fake)'], ['nan', 'Well done darling! Don’t spend it all on scratchcards x'], ['tash', 'buy a horse. a small one. for me'], ['kev', 'naming my firstborn {profit}']],
  clear:    [['kev', 'CLEAN SWEEP. I need a lie down'], ['dave', 'not one mine. who ARE you'], ['priya', 'the board is naked now. look away'], ['nan', 'Very tidy love, like your grandad’s shed x'], ['tash', 'the full clear. disgusting. iconic']],
  don_offer:[['dave', 'do it. do it. do it.'], ['tash', 'the voices say yes. the voices are me'], ['nan', 'I wouldn’t love'], ['kev', 'I’m watching through my fingers'], ['priya', 'the maths says walk away. I say nothing']],
  don_win:  [['dave', 'NO WAY'], ['tash', 'ICON. LEGEND. MOTHER.'], ['priya', 'the odds said no. you said yes'], ['kev', 'I just stood up at my desk'], ['nan', 'Ooh lovely x']],
  don_lose: [['dave', 'oh no. oh no no no'], ['tash', 'rip to your entire run'], ['nan', 'Never mind love. Money is just paper with ghosts in x'], ['kev', 'pour one out']],
  bust:     [['nan', 'Come round for tea love, I’ll do you a sandwich x'], ['dave', 'from hero to zero'], ['tash', 'changing the group name to “skint”'], ['priya', 'respectfully: lmao'], ['kev', 'the goblin is going through your bins now']],
  buy:      [['kev', 'ooh shiny'], ['priya', 'investing in yourself, love that'], ['dave', 'what does that even do'], ['nan', 'Is that one of those NFTs love? x'], ['tash', 'spending money to make money. classic']],
  addon:    [['kev', 'ooh a little card'], ['tash', 'that card is doing something illegal'], ['priya', 'that card is giving main character'], ['dave', 'is that one of them lucky cards']],
  unlock:   [['dave', 'new table who dis'], ['tash', 'moving up in the world'], ['kev', 'the carpet in there is sticky in a good way'], ['nan', 'Is that the one with the nice carpet? x']],
  ascend:   [['dave', 'ASCENSION? in THIS economy?'], ['priya', 'more mines, more money. sounds legal'], ['kev', 'you’re glowing. is that radiation'], ['tash', 'the tables look angrier already']],
  streak:   [['tash', '{streak} in a row?? on fire'], ['dave', 'heater. absolute heater'], ['kev', 'don’t jinx it don’t jinx it'], ['priya', 'statistically this has to end. not my problem though']],
  coward:   [['tash', 'the robot chickened out lmao'], ['nan', 'The robot has more sense than your grandad x']],
  yolo:     [['dave', 'the robot is gambling now. we’ve created a monster'], ['tash', 'the robot is in its villain era']],
  flip_win: [['priya', 'coin respected you'], ['nan', 'I always pick heads love. Or tails. One of them x']],
  flip_lose:[['tash', 'the coin hates you specifically'], ['kev', 'it was always going to be the other side']],
  shield:   [['priya', 'saved by the shield!'], ['dave', 'plot armour']],
  fuse:     [['dave', 'the bomb went “pfft” lmao'], ['kev', 'damp squib. literally']],
  gem:      [['tash', 'SHINY'], ['kev', 'a gem! like you'], ['priya', 'that’s going in the vault'], ['nan', 'Ooh sparkly x'], ['dave', 'pocket it before the goblin sees']],
  jackpot:  [['dave', 'JACKPOT. I’m crying in a Wetherspoons'], ['tash', 'SCREAMING. CRYING. THROWING UP.'], ['nan', 'Ooh, that’s the fruit machine noise! x']],
  golden:   [['priya', 'a golden board?? manifest it'], ['kev', 'everything is shiny and I’m scared']],
  levelup:  [['priya', 'level up! growth!'], ['nan', 'Well done love, I’ve told the whole street x'], ['kev', 'you’re officially a {rank} now'], ['dave', '{rank}? put it on your CV']],
  spin:     [['tash', 'spin the wheel spin the wheel'], ['kev', 'the wheel is my higher power now']],
  casino:   [['nan', 'My grandchild owns a CASINO x'], ['dave', 'I’m telling everyone I knew you before'], ['tash', 'free drinks forever right? right??']],
  // around the house: the noises (odd_ + the noise's name), then how the household events went
  odd_smoke:     [['kev', 'is that the smoke alarm'], ['nan', 'That’s the smoke alarm love, it wants a new battery x'], ['tash', 'that chirp is going to live in my head rent free'],
    ['dave', 'it’ll do that once a minute for three weeks. it’s tradition'], ['priya', 'we are all being haunted by one small battery'], ['dave', 'they only ever run out at 3am. it’s in the contract']],
  odd_alarm:     [['nan', 'Who’s burnt the toast? x'], ['tash', 'the smoke alarm is screaming. so am I'], ['dave', 'open a window and wave a tea towel. the British way']],
  odd_knock:     [['dave', 'don’t answer it. it’s the bailiffs'], ['tash', 'knock knock. who’s there. your debts'], ['kev', 'pretend you’re not in'], ['nan', 'Is that the man about the gutters? x']],
  odd_doorbell:  [['dave', 'don’t answer it. it’s the bailiffs'], ['tash', 'expecting someone? ;)'], ['priya', 'nobody rings a doorbell anymore. it’s either the police or a cult']],
  odd_phone:     [['nan', 'Is that the landline? Nobody rings the landline x'], ['dave', 'it’s a scammer. it’s always a scammer'], ['kev', 'let it ring. it’s 2026']],
  odd_kittens:   [['tash', 'KITTENS??'], ['nan', 'Has someone left kittens on the step? x'], ['priya', 'drop everything. kittens'], ['dave', 'is that a kitten or the wifi router dying']],
  odd_ducks:     [['priya', 'why are there ducks'], ['dave', 'the ducks are unionising'], ['kev', 'I hear the ducks before the bombs now'], ['tash', 'the ducks know something']],
  odd_duck:      [['priya', 'why is there a duck'], ['dave', 'quack'], ['nan', 'Save your crusts for the ducks love x']],
  odd_squeak:    [['kev', 'was that the dog or you'], ['tash', 'who’s squeezing the toy'], ['dave', 'the dog’s winning more than you']],
  odd_carAlarm:  [['dave', 'is that my car'], ['kev', 'car alarms have never once stopped a crime'], ['tash', 'some poor sod’s car is having a breakdown']],
  odd_microwave: [['tash', 'who’s microwaving fish at this hour'], ['dave', 'your pizza’s done']],
  odd_buzz:      [['priya', 'your phone’s going'], ['kev', 'is that the bank calling']],
  odd_kettle:    [['nan', 'Ooh put one on for me love x'], ['priya', 'tea break?? mid-game??']],
  odd_fart:      [['tash', 'who did that'], ['kev', 'not me'], ['dave', 'better out than in']],
  odd_creak:     [['dave', 'did anyone else hear that door'], ['nan', 'Is somebody there? x']],
  odd_meow:      [['nan', 'Has someone fed the cat? x'], ['tash', 'KITTY']],
  odd_gull:      [['dave', 'is that a seagull? we’re nowhere near the sea'], ['nan', 'Don’t feed it love, they bite x'], ['tash', 'SEAGULL. GUARD YOUR CHIPS'],
    ['kev', 'that gull has a criminal record. I’ve seen the posters'], ['priya', 'it’s looking at your coins. it’s LOOKING at them']],
  odd_powerdown: [['dave', 'who didn’t top up the meter'], ['nan', 'Has the electric gone? I’ll get the candles love x'], ['tash', 'LIGHTS OUT. I can’t see my own mines'],
    ['kev', 'playing by the light of my phone. it’s on 4%'], ['priya', 'this is the most British thing that’s ever happened in this chat']],
  power_back:    [['dave', 'power’s back. we are SO back'], ['nan', 'Ooh that’s better. Blow the candles out love x'], ['kev', 'I’d just got used to the dark'],
    ['priya', 'emergency credit: the only credit you’ve got']],
  power_topup:   [['priya', 'a responsible adult topped up the meter'], ['tash', 'look at you, paying bills'], ['dave', 'money well spent. probably'],
    ['nan', 'Good. You’ll ruin your eyes playing in the dark x']],
  power_win:     [['tash', 'cashing out in the DARK. absolute cinema'], ['dave', 'danger money! DANGER MONEY!'], ['kev', 'you can’t even see the mines and you’re winning'],
    ['priya', 'the dark suits you']],
  gull_shoo:     [['dave', 'get in. the gull’s been told'], ['tash', 'you fought a seagull and won. legend'], ['nan', 'Wave your arms at them love, works every time x'],
    ['priya', 'it’ll be back. with friends'], ['kev', 'the gull’s filing a complaint']],
  gull_nicked:   [['dave', 'the seagull mugged you'], ['kev', 'it’s at the chippy now, spending your money'], ['tash', 'beaten by a bird. a BIRD'],
    ['priya', 'the gull knows your PIN now'], ['nan', 'Cheeky thing! They had your grandad’s pasty in Padstow once x']],
  chirp_again:   [['tash', 'it’s still chirping'], ['dave', 'CHANGE. THE. BATTERY.'], ['kev', 'I can hear it through the chat somehow'], ['nan', 'Use the kitchen chair love, not the wobbly one x'],
    ['priya', 'that chirp has more staying power than my last three relationships']],
  battery_ok:    [['dave', 'silence. beautiful silence'], ['tash', 'a hero. a DIY hero'], ['nan', 'Your grandad never changed one in forty years x'], ['kev', 'was it a 9 volt. I could feel it was a 9 volt']],
  battery_fall:  [['dave', 'I heard that from here'], ['tash', 'are you alive'], ['nan', 'Not the wobbly chair! x'], ['priya', 'the chirp won. the chirp always wins']],
  door_good:     [['nan', 'See, it pays to answer the door x'], ['dave', 'free stuff from the door. the door is your friend now'], ['kev', 'I never answer the door and look at me']],
  door_bad:      [['dave', 'told you not to answer it'], ['tash', 'the door giveth and the door taketh away'], ['priya', 'and that’s why I live in a cupboard'], ['kev', 'lesson learned: never open the door']],
  door_weird:    [['priya', 'what just happened'], ['kev', 'I have questions'], ['tash', 'your door is cursed and I love it'], ['nan', 'Was it the nice young man with the leaflets? x']],
  phone:         [['dave', 'who was it'], ['nan', 'Was it me? I can’t remember if I rang x'], ['tash', 'you answered a phone call? brave'], ['kev', 'I haven’t answered a call since 2019']],
  kitten_pet:    [['tash', 'PROTECT THE KITTEN'], ['nan', 'Give it a bit of ham love x'], ['priya', 'the kitten is the CEO now'], ['kev', 'I would die for that kitten'], ['dave', 'put the kitten on the payroll']],
  kitten_gone:   [['tash', 'you let the kitten LEAVE??'], ['priya', 'a kitten walked past and you didn’t even look. monster'], ['nan', 'It’ll be back when it’s hungry love x']],
  toast:         [['nan', 'Scrape the black bits off love, it’s fine x'], ['dave', 'burnt toast is just toast with ambition'], ['kev', 'I like it burnt. I’m not well'], ['priya', 'the tea towel wave. a British classic']],
  raffle_win:    [['nan', 'I’ve never won a raffle in my life! x'], ['dave', 'roof funded. children saved. legend'], ['tash', 'rigged. love it']],
  raffle_lose:   [['kev', 'the roof thanks you'], ['dave', 'charity is its own reward. the reward is nothing'], ['priya', 'it’s for the kids. the kids won']],
  // scratchcards
  scratch_buy:   [['nan', 'Get me a Lucky Dip while you’re there love x'], ['kev', 'scratch it with a 2p, it’s luckier'], ['dave', 'buy two, the second one’s always the winner']],
  scratch_win:   [['nan', 'I used to buy one every Saturday with your grandad. Never won a sausage x'], ['dave', 'SCRATCH KING'],
    ['kev', 'I’ve never won more than a quid on those'], ['tash', 'frame it. frame the card'], ['priya', 'the newsagent will remember this day']],
  scratch_evens: [['priya', 'money back. the most British win possible'], ['kev', 'technically not a loss']],
  scratch_lose:  [['tash', 'the corner shop thanks you'], ['priya', 'the odds are printed on the back. nobody reads the back'], ['kev', 'two crowns and a coin. so close'],
    ['dave', 'should’ve bought a meal deal']],
  // the pub quiz ({answer} is the right one)
  quiz_right:    [['dave', 'alright Einstein'], ['tash', 'nerd. (correct though)'], ['kev', 'you’re on the quiz team now'], ['nan', 'Clever clogs! Your grandad would be proud x'],
    ['priya', 'points to the big brain']],
  quiz_wrong:    [['dave', 'WRONG. it was {answer}'], ['nan', 'Never mind love, it was {answer} x'], ['kev', '{answer}. I knew that. I did not know that'],
    ['priya', 'the answer was {answer}. we don’t talk about this'], ['tash', 'it was {answer} babe']],
  quiz_slow:     [['dave', 'too slow. it was {answer}'], ['tash', 'asleep? it was {answer}'], ['nan', 'The answer was {answer} love. I got it straight away x']],
  // the duck race
  grass_back:    [['nan', 'There, doesn’t that feel better love? x'], ['priya', 'you went OUTSIDE? on purpose?'], ['kev', 'what’s it like out there. is it nice'],
    ['tash', 'touched grass. character development'], ['dave', 'the mines missed you. they said']],
  grass_early:   [['nan', 'That wasn’t three minutes love x'], ['dave', 'lasted about as long as your last streak'], ['priya', 'the grass barely felt it'],
    ['tash', 'speedrunning fresh air']],
  // thunderstorms
  odd_thunder:   [['nan', 'Was that thunder? I’ve got washing out x'], ['kev', 'the dog’s gone under the bed. storm’s coming'], ['priya', 'that was thunder. the sky is about to get involved']],
  storm_start:   [['nan', 'Unplug the telly love, there’s a storm x'], ['tash', 'the weather’s gone biblical'], ['kev', 'count between the flash and the bang. that’s how many miles. I think'],
    ['priya', 'watch the boards when it flashes. you can see the mines. science'], ['dave', 'perfect weather for losing money indoors']],
  storm_flash:   [['tash', 'DID YOU SEE THAT'], ['kev', 'one Mississippi… two Mississippi…'], ['priya', 'did you get them? the mines? tell me you got them'], ['nan', 'Ooh that was a big one x']],
  storm_strike:  [['tash', 'THAT WAS RIGHT ON TOP OF US'], ['kev', 'it hit the substation. I heard it'], ['nan', 'Oh my days, the lights! x'], ['priya', 'zero Mississippi. that’s not great']],
  storm_end:     [['nan', 'That’s blown over now love x'], ['kev', 'sun’s out. there’s a rainbow over the bins'], ['tash', 'storm’s gone. the drama isn’t'], ['priya', 'and just like that, the mines are invisible again']],
  // the Fruity
  fruity_win:    [['kev', 'told you it was due'], ['tash', 'FRUIT'], ['priya', 'the machine giveth'], ['nan', 'Ooh lovely, get yourself a lemonade love x'],
    ['dave', 'lemons. how fitting'], ['kev', 'it’s warming up now. I can feel it']],
  fruity_big:    [['tash', 'RING RING. that’s the bells'], ['kev', 'IT WAS DUE. I SAID IT WAS DUE'], ['priya', 'statistically that was always going to happen eventually'],
    ['dave', 'right, your round then'], ['nan', 'Well I never! Put some of that away for a rainy day love x']],
  fruity_jackpot: [['tash', 'THREE SEVENS. I AM SCREAMING'], ['kev', 'I put forty quid in that machine last week and you walk up and do THAT'],
    ['nan', 'Jackpot! Don’t tell your grandad x'], ['dave', 'the booth’s going to need a new float'], ['priya', 'I’m framing a screenshot of this']],
  fruity_nudge:  [['kev', 'nudge nudge'], ['tash', 'the nudge of a lifetime'], ['priya', 'surgical'], ['dave', 'even a stopped clock nudges right twice a day']],
  fruity_hold:   [['kev', 'HOLD THEM. HOLD THEM BOTH'], ['tash', 'hold everything. hold my drink'], ['nan', 'Hold the nice ones love x']],
  fruity_dry:    [['kev', 'it’s due mate. it’s got to be due'], ['priya', 'kev it doesn’t remember what it did last time'], ['nan', 'Those machines are a mug’s game love x'],
    ['dave', 'feed it another one, it looks hungry'], ['kev', 'the trick is you have to talk to it']],
  fruity_double: [['tash', 'DOUBLE'], ['kev', 'let it ride'], ['priya', 'every gamble’s a coin flip. you know that right'], ['dave', 'go again. coward if you don’t']],
  fruity_gone:   [['dave', 'and it’s gone'], ['priya', 'that’s why it’s called gambling'], ['nan', 'Oh love x'], ['kev', 'unlucky. it was due though']],
  bingo_buy:     [['nan', 'Eyes down love! I’ll call them nice and slow x'], ['dave', 'bingo? what are you, 80?'], ['kev', 'got my lucky dabber'], ['priya', 'bingo is just minesweeper for nans']],
  bingo_line:    [['nan', 'A line! Well done love x'], ['tash', 'LINE! somebody check it'], ['dave', 'a line. adorable'], ['kev', 'I was sweating on 47 the whole time']],
  bingo_two:     [['nan', 'Two lines! I nearly dropped my sherry x'], ['tash', 'TWO LINES. the hall is in uproar'], ['priya', 'the regulars are glaring at you']],
  bingo_house:   [['nan', 'HOUSE!!! You’ve won the big one love!! x'], ['dave', 'FULL HOUSE?? I’m coming to bingo next week'], ['tash', 'the whole community centre just booed you. iconic'],
    ['kev', 'I’ve played bingo for 11 years and never had a house']],
  bingo_lose:    [['nan', 'Never mind love, there’s always next week x'], ['dave', 'not even a line. the nans are laughing at you'], ['kev', 'I needed 23 for the whole game'],
    ['priya', 'bingo’s rigged. ask any nan']],
  duck_start:    [['dave', 'COME ON THE YELLOW ONE'], ['tash', 'my money’s on whichever one looks the most unhinged'], ['kev', 'the ducks are on something. I can tell'],
    ['nan', 'Which one’s ours love? x'], ['priya', 'I’ve got a tenner on the slowest one. for the story']],
  duck_win:      [['dave', 'THE DUCK DID IT'], ['tash', 'that duck deserves a knighthood'], ['nan', 'Lovely ducks x'], ['kev', 'I’m crying. over a duck'], ['priya', 'bread for that duck. all of the bread']],
  duck_lose:     [['dave', 'that duck threw the race'], ['tash', 'your duck stopped for a snack'], ['kev', 'the duck was paid off. I’ve seen it before'], ['priya', 'never trust a duck'],
    ['nan', 'Never mind love, they’re all winners really x']],
};
// The ruder lines. They join the pools above unless "Rude chat" is switched off in Stats.
export const RUDE = {
  hello:     [['dave', 'right, you degenerates, who’s in'], ['tash', 'back again? your bank must be thrilled'], ['kev', 'told the wife I’m at the gym'], ['priya', 'welcome back to bad decisions']],
  deal_big:  [['dave', 'absolute madman'], ['kev', 'you’re going to lose that, aren’t you'], ['tash', 'oh for god’s sake'], ['priya', 'your pension just called. it was crying']],
  boom:      [['dave', 'you absolute muppet'], ['tash', 'oh you plonker'], ['nan', 'Oh bugger x'], ['kev', 'bollocks. sorry. but bollocks'], ['priya', 'skill issue'], ['dave', 'clicked it like it owed you money']],
  cash_small:[['dave', 'what is that, a tip?'], ['tash', 'wow. a whole sandwich'], ['kev', 'cowardly. but profitable']],
  cash_big:  [['dave', 'you jammy git'], ['tash', 'you lucky cow'], ['kev', 'buy me a pint, you tight sod']],
  clear:     [['dave', 'show-off'], ['tash', 'you look smug. I can tell from here']],
  bust:      [['dave', 'skint. absolutely skint'], ['tash', 'you gambled the rent, didn’t you'], ['kev', 'who’s telling your mum'], ['priya', 'rock bottom has a basement. welcome']],
  don_offer: [['dave', 'don’t be a wuss'], ['tash', 'what’s the worst that could happen (everything)'], ['kev', 'my therapist says I shouldn’t watch this']],
  don_lose:  [['dave', 'well that was bloody stupid'], ['tash', 'HAHAHAHA. sorry. HAHAHA'], ['kev', 'that’s a crime against money']],
  buy:       [['dave', 'you got mugged off'], ['tash', 'that’s a rip-off and you know it']],
  flip_lose: [['dave', 'the coin mugged you off'], ['tash', 'unlucky. no actually, you’re just bad']],
  levelup:   [['dave', 'levelling up at gambling. your mum must be so proud']],
  streak:    [['dave', 'don’t get cocky']],
  jackpot:   [['dave', 'you jammy, jammy sod']],
  duck_lose: [['dave', 'useless bloody duck'], ['tash', 'that duck can get stuffed. with orange sauce']],
  scratch_lose: [['dave', 'absolute mug'], ['tash', 'scratching away your rent money, lovely']],
  quiz_wrong: [['tash', 'it was {answer}, you absolute walnut'], ['dave', '{answer}, you muppet']],
  door_bad:  [['dave', 'absolute pillocks'], ['tash', 'they took the LAMP?? the bloody cheek']],
  battery_fall: [['kev', 'arse over tit. a classic'], ['dave', 'did you land on your arse or your face']],
  chirp_again: [['tash', 'CHANGE THE BLOODY BATTERY']],
  kitten_gone: [['dave', 'you heartless git']],
  odd_fart:  [['dave', 'whoever smelt it dealt it'], ['tash', 'kev that’s disgusting'], ['kev', 'IT WASN’T ME']],
  odd_carAlarm: [['dave', 'turn it off, you absolute weapon']],
  gull_nicked: [['dave', 'mugged off by a flying rat'], ['tash', 'robbed by a pigeon with a gym membership']],
  odd_gull:  [['dave', 'flying rat incoming']],
  grass_early: [['dave', 'couldn’t even manage three minutes. addict'], ['tash', 'back already, you absolute goblin']],
  bingo_lose: [['dave', 'beaten at bingo by a load of pensioners. pathetic'], ['tash', 'not a sodding line']],
  fruity_dry: [['dave', 'you’re feeding a fruit machine. in a booth. on your own'], ['tash', 'absolute mug behaviour']],
  storm_start: [['dave', 'the sky’s trying to smite your stake'], ['tash', 'it’s absolutely chucking it down, the gutters are crying']],
  fruity_gone: [['dave', 'greedy. absolute mug'], ['tash', 'gambled it away like a muppet']],
  odd_powerdown: [['dave', 'put a quid in the meter, you tight git'], ['tash', 'who’s been running the tumble dryer']],
  power_back: [['tash', 'about bloody time']],
};
export const CHANCE = { duck_start: .6, boom: .7, cash_small: .3, cash_big: .9, clear: .9, deal_big: .8, buy: .5, addon: .6, coward: .25, yolo: .3, streak: .8, fuse: .8, gem: .35, golden: .7, spin: .5 };
// Double or Nothing asks this before each rung of the ladder.
export const SURE = ['Are you sure?', 'Are you SURE sure?', 'Mate. Are you actually sure?', 'This is where sensible people stop.', 'Nan is crying. Are you sure?'];
