// Ambient group-chat conversations.

// Little conversations the group chat has on its own, unprompted. Nobody asked for them.
export const THREADS = [
  [['kev', 'anyone know how to get a seagull out of a car'], ['dave', 'why is there a seagull in your car'], ['kev', 'that is not what I asked']],
  [['nan', 'Who is Bluetooth and why does he want to pair with me x']],
  [['tash', 'my sourdough starter just said my name'], ['priya', 'what did it sound like'], ['tash', 'yeasty']],
  [['dave', 'hear me out. cargo shorts but for your arms']],
  [['priya', 'found a tooth in my coat pocket. not mine. not asking.']],
  [['kev', 'the yoghurt in the office fridge is from 2021. it has a name now. it’s Gary']],
  [['nan', 'I’ve joined a gang love. It’s the knitting circle but we’re very dangerous x']],
  [['tash', 'just saw two pigeons holding hands outside Tesco'], ['dave', 'love wins'], ['kev', 'pigeons don’t have hands'], ['tash', 'they made it work']],
  [['dave', 'my landlord texted “u up” about the boiler']],
  [['priya', 'a group of flamingos is called a flamboyance. that’s it. that’s the message']],
  [['kev', 'accidentally replied-all “love you” to the whole company'], ['tash', 'and?'], ['kev', 'HR said it back']],
  [['nan', 'What does “slay” mean? Your cousin said it about my trifle x'], ['tash', 'it means your trifle is iconic nan'], ['nan', 'Oh lovely. It is x']],
  [['dave', 'my mum just asked what minesweeper is. she’s on Ascension II now']],
  [['priya', 'alexa added condoms to my shopping cart again'], ['priya', 'I don’t own an alexa'], ['kev', 'who is in your house priya']],
  [['tash', 'my gaydar just pinged the toaster'], ['dave', 'the toaster is bi. everyone knows that']],
  [['kev', 'the vending machine at work gave me two KitKats. I think it likes me']],
  [['dave', 'anyone want a slightly used trampoline. it’s on my roof. don’t ask how']],
  [['nan', 'Can someone tell the man in my phone to stop talking x'], ['priya', 'nan that’s a podcast'], ['nan', 'Well he’s very rude x']],
  [['priya', 'I’ve started talking to the goblin. he gets me']],
  [['kev', 'sorry if I’m quiet. at goat yoga. a goat is on me. I live here now']],
  [['tash', 'I have never seen a baby pigeon. where are they keeping them']],
  [['dave', 'the bomb winked at me. I saw it. I’m not well']],
  [['nan', 'Your grandad played minesweeper. Never cashed out once. He’s fine, he lives in Margate now x']],
  [['priya', 'today’s affirmation: I am a mine and nobody can stop me']],
  [['kev', 'is anyone else’s carbon monoxide alarm chirping or is it just my soul']],
  [['tash', 'new life goal: be as confident as a pigeon walking into Greggs']],
  [['dave', 'me and the lads are starting a band. we’re called Unrevealed Tile'], ['tash', 'first album?'], ['dave', '“Cashed Out Too Early”']],
  [['nan', 'I put a bet on the horses love. I don’t know which horses. I just shouted x']],
  [['kev', 'just realised I left my crocs in sport mode at a funeral']],
  [['tash', 'is it gay to have a favourite tile? asking for a 7']],
  [['dave', 'opened a fortune cookie and it just said “cash out”'], ['kev', 'did you'], ['dave', 'no']],
  [['nan', 'The cat brought me a whole sausage roll x'], ['tash', 'where did it get a sausage roll'], ['nan', 'Don’t ask questions love x']],
  [['priya', 'my horoscope says “avoid mines”. bit specific'], ['kev', 'what’s your sign'], ['priya', 'flag']],
  [['kev', 'my smart fridge just asked if I’m ok']],
  [['tash', 'pride month is twelve months long if you’re brave enough']],
];
