// The pub quiz: questions the group chat asks now and then. The first answer is the right one (they're shuffled on screen).

export const QUIZ = [
  // general knowledge, mostly from round here
  ['What’s the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne'],
  ['How many sides does a 50p coin have?', 'Seven', 'Six', 'Eight'],
  ['What’s the national animal of Scotland?', 'A unicorn', 'A stag', 'A golden eagle'],
  ['How many players does a rugby union team have on the pitch?', '15', '13', '11'],
  ['What year did the UK go decimal?', '1971', '1966', '1979'],
  ['What’s the chemical symbol for gold?', 'Au', 'Ag', 'Gd'],
  ['How many hearts does an octopus have?', 'Three', 'One', 'Eight'],
  ['What’s a group of crows called?', 'A murder', 'A parliament', 'A gaggle'],
  ['Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Mars'],
  ['What’s the longest river in the UK?', 'The Severn', 'The Thames', 'The Trent'],
  ['What’s the highest mountain in Wales?', 'Yr Wyddfa (Snowdon)', 'Pen y Fan', 'Cadair Idris'],
  ['How many minutes are there in a day?', '1,440', '1,240', '1,640'],
  ['What’s the dot on a lowercase i called?', 'A tittle', 'A jot', 'A pip'],
  ['What’s the smallest prime number?', '2', '1', '3'],
  ['Who wrote Romeo and Juliet?', 'Shakespeare', 'Dickens', 'Chaucer'],
  ['How many bones are in an adult human body?', '206', '186', '226'],
  ['What’s the largest ocean?', 'The Pacific', 'The Atlantic', 'The Indian'],
  ['What’s the freezing point of water in Fahrenheit?', '32', '0', '12'],
  ['What year did people first land on the Moon?', '1969', '1966', '1972'],
  ['What’s the currency of Japan?', 'The yen', 'The won', 'The yuan'],
  ['What’s a male duck called?', 'A drake', 'A gander', 'A cob'],
  ['What’s a group of kittens called?', 'A kindle', 'A clowder', 'A pounce'],
  ['What’s the hardest natural substance?', 'Diamond', 'Quartz', 'Granite'],
  ['Which city is known as the Steel City?', 'Sheffield', 'Leeds', 'Newcastle'],
  ['What does the M25 go round?', 'London', 'Birmingham', 'Manchester'],
  ['Strictly speaking, what is Big Ben?', 'The bell', 'The tower', 'The clock'],
  ['What’s a baby kangaroo called?', 'A joey', 'A kit', 'A cub'],
  ['How many squares are on a chessboard?', '64', '48', '81'],
  ['What’s the square root of 144?', '12', '14', '16'],
  ['Which gas do plants take in?', 'Carbon dioxide', 'Oxygen', 'Nitrogen'],
  ['What’s the largest mammal?', 'The blue whale', 'The African elephant', 'The sperm whale'],
  ['Which of these birds can’t fly?', 'The penguin', 'The puffin', 'The pigeon'],
  // gambling and minesweeper
  ['How many cards are in a deck, without the jokers?', '52', '54', '48'],
  ['In blackjack, what total are you after?', '21', '24', '18'],
  ['What colour is the zero on a roulette wheel?', 'Green', 'Red', 'Black'],
  ['How many numbers are on a European roulette wheel, zero included?', '37', '36', '38'],
  ['The spots on a die add up to…', '21', '20', '24'],
  ['Opposite faces of a die always add up to…', 'Seven', 'Six', 'Eight'],
  ['On Expert minesweeper (30 by 16), how many mines are there?', '99', '40', '120'],
  ['In classic minesweeper, what colour is a 1?', 'Blue', 'Green', 'Red'],
  ['In classic minesweeper, what colour is a 3?', 'Red', 'Green', 'Purple'],
  ['How many tiles can touch one tile in minesweeper?', 'Eight', 'Four', 'Six'],
  ['Which Windows first came with Minesweeper built in?', 'Windows 3.1', 'Windows 95', 'Windows XP'],
  // this game
  ['Who taught you to play this game?', 'Fuse the bomb', 'Nan', 'Big Dave'],
  ['What did Big Dave borrow in 2019?', 'A tenner', 'A lawnmower', 'A fiver'],
  ['What’s the yoghurt in Kev’s office fridge called?', 'Gary', 'Kevin', 'Steve'],
  ['Where does Grandad live now?', 'Margate', 'Skegness', 'Bognor'],
  ['What wants a new battery at 3am?', 'The smoke detector', 'The kettle', 'Nan'],
  ['What’s a jackpot gem worth?', '×5', '×10', '×3'],
];
// how a friend opens the round
export const QUIZ_INTROS = ['QUIZ TIME.', 'pub quiz, round one.', 'quick one for you:', 'settle an argument:', 'right, general knowledge:', 'Quiz question love x'];
