// Exports the web game's rules and jokes for the terminal versions, so every version plays by the same numbers:
//   ports/python/rules.json   ports/kotlin/src/Rules.kt   ports/csharp/Rules.cs
// It also plays a few Daily Challenges with a fixed strategy and stores the results ("golden" runs). Each port's
// self-test (--selftest) must reproduce those exactly: same boards, same moves, same multipliers.
// Run it after changing src/data, src/content or the daily:   node tools/export_rules.mjs
// node tools/export_rules.mjs --check   only reports whether the ports are out of date (used by test/ports.py)
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { START, TABLES, BOOST, CLEAR, GOLDEN, LADDER, CASINO } from '../src/data/economy.js';
import { GEMS } from '../src/data/gems.js';
import { FRIENDS, LINES, RUDE, SURE } from '../src/content/chat-lines.js';
import { QUIPS, RUDE_QUIPS } from '../src/content/quips.js';
import { DAILY, Daily } from '../src/game/daily.js';
import { Solver } from '../src/board/solver.js';
import { S } from '../src/core/state.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const GOLDEN_KEYS = ['2026-10-06', '2026-12-25', '2027-02-28', '2030-01-01'];

// ---------- the data ----------
const tables = TABLES.map(({ id, name, w, h, m, gems, lim, prog, min, cap, cost, blurb }) => ({ id, name, w, h, m, gems, lim, prog, min, cap, cost, blurb }));
const gems = GEMS.map(({ k, x, w, name }) => ({ k, x, w, name }));
const friends = Object.fromEntries(Object.entries(FRIENDS).map(([k, f]) => [k, f.name]));
// the terminal versions get the rude lines too (the web game has a switch for them in Stats)
const lines = Object.fromEntries(Object.entries(LINES).map(([k, v]) => [k, v.concat(RUDE[k] || []).map(([who, text]) => [who, text])]));
const styles = Object.entries(DAILY.styles).map(([who, [boom, lo, hi]]) => ({ who, boom, lo, hi }));

// ---------- golden boards + golden runs (the strategy every port replays) ----------
function play(key, maxDigs = 12) {
  const b = Daily.create(key);
  for (let step = 0; step < maxDigs && !b.over; step++) {
    const d = Solver.full(b);
    let pick = -1;
    for (let i = 0; i < b.n; i++) if (!b.open[i] && !b.flag[i] && d.KS[i]) { pick = i; break; }
    if (pick < 0) { let best = 2; for (let i = 0; i < b.n; i++) { if (b.open[i] || b.flag[i] || d.P[i] >= 1) continue; if (d.P[i] < best) { best = d.P[i]; pick = i; } } }
    if (pick < 0) break;
    Daily.dig(b, pick);
  }
  if (!b.over) Daily.cash(b);
  const r = S_last();
  return { key, moves: r.moves, revealed: b.revealed, mult: r.mult, why: r.why };
}
const S_last = () => S.life.daily.result;
const golden = GOLDEN_KEYS.map(key => {
  const b = Daily.create(key);
  const g = []; for (let i = 0; i < b.n; i++) if (b.gem[i]) g.push([i, b.gem[i]]);
  return { key, number: Daily.number(key), mines: Array.from(b.mine).join(''), open: Array.from(b.open).join(''), gems: g,
    friends: Daily.friends(key).map(f => [f.who, f.mult]) };
});
const runs = GOLDEN_KEYS.map(key => play(key));

const rules = { START, BOOST, CLEAR, GOLDEN, LADDER, CASINO, tables, gems, friends, lines, sure: SURE, quips: QUIPS.concat(RUDE_QUIPS),
  daily: { epoch: DAILY.epoch, table: DAILY.table, limit: DAILY.limit, gems: DAILY.gems, prize: DAILY.prize, seed: DAILY.seed, chatSeed: DAILY.chatSeed, styles },
  golden, runs };

// ---------- writers ----------
const NOTE = 'Generated by tools/export_rules.mjs from the web game (src/data, src/content, src/game/daily.js). Don’t edit by hand.';
const files = new Map();
const out = (rel, text) => files.set(rel, text);
const dbl = x => { const s = String(x); return /[.e]/.test(s) ? s : s + '.0'; };

// Python reads JSON
out('ports/python/rules.json', JSON.stringify({ _note: NOTE, ...rules }, null, 1) + '\n');

// Kotlin
const kq = s => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$').replace(/\n/g, '\\n') + '"';
out('ports/kotlin/src/Rules.kt', `// ${NOTE}
package sweepstakes

data class Table(val id: String, val name: String, val w: Int, val h: Int, val m: Int, val gems: Int, val lim: Double,
                 val prog: Double, val min: Double, val cap: Double, val cost: Double, val blurb: String)
data class GemTier(val k: String, val x: Double, val w: Double, val name: String)
data class Style(val who: String, val boom: Double, val lo: Double, val hi: Double)
data class GoldenBoard(val key: String, val number: Int, val mines: String, val open: String, val gems: List<Pair<Int, Double>>, val friends: List<Pair<String, Double>>)
data class GoldenRun(val key: String, val moves: List<String>, val revealed: Int, val mult: Double, val why: String)

object Rules {
    const val START = ${START}L
    const val BOOST = ${dbl(BOOST)}
    const val CLEAR = ${dbl(CLEAR)}
    const val GOLDEN = ${dbl(GOLDEN)}
    const val CASINO = ${dbl(CASINO)}
    val LADDER = listOf(${LADDER.join(', ')})
    val TABLES = listOf(
${tables.map(t => `        Table(${kq(t.id)}, ${kq(t.name)}, ${t.w}, ${t.h}, ${t.m}, ${t.gems}, ${dbl(t.lim)}, ${dbl(t.prog)}, ${dbl(t.min)}, ${dbl(t.cap)}, ${dbl(t.cost)}, ${kq(t.blurb)})`).join(',\n')})
    val GEMS = listOf(${gems.map(g => `GemTier(${kq(g.k)}, ${dbl(g.x)}, ${dbl(g.w)}, ${kq(g.name)})`).join(', ')})
    val FRIENDS = mapOf(${Object.entries(friends).map(([k, v]) => `${kq(k)} to ${kq(v)}`).join(', ')})
    val SURE = listOf(${SURE.map(kq).join(', ')})
    val QUIPS = listOf(
${QUIPS.map(q => '        ' + kq(q)).join(',\n')})
    val LINES: Map<String, List<Pair<String, String>>> = mapOf(
${Object.entries(lines).map(([k, v]) => `        ${kq(k)} to listOf(${v.map(([w, t]) => `${kq(w)} to ${kq(t)}`).join(', ')})`).join(',\n')})
    val DAILY_EPOCH = listOf(${DAILY.epoch.join(', ')})
    const val DAILY_TABLE = ${kq(DAILY.table)}
    const val DAILY_LIMIT = ${dbl(DAILY.limit)}
    const val DAILY_GEMS = ${DAILY.gems}
    const val DAILY_PRIZE = ${dbl(DAILY.prize)}
    const val DAILY_SEED = ${kq(DAILY.seed)}
    const val DAILY_CHAT_SEED = ${kq(DAILY.chatSeed)}
    val DAILY_STYLES = listOf(${styles.map(s => `Style(${kq(s.who)}, ${dbl(s.boom)}, ${dbl(s.lo)}, ${dbl(s.hi)})`).join(', ')})
    val GOLDEN_BOARDS = listOf(
${golden.map(g => `        GoldenBoard(${kq(g.key)}, ${g.number}, ${kq(g.mines)}, ${kq(g.open)}, listOf(${g.gems.map(([i, x]) => `${i} to ${dbl(x)}`).join(', ')}), listOf(${g.friends.map(([w, m]) => `${kq(w)} to ${dbl(m)}`).join(', ')}))`).join(',\n')})
    val GOLDEN_RUNS = listOf(
${runs.map(r => `        GoldenRun(${kq(r.key)}, listOf(${r.moves.map(kq).join(', ')}), ${r.revealed}, ${dbl(r.mult)}, ${kq(r.why)})`).join(',\n')})
}
`);

// C# (C# 7 syntax so it builds with Mono's mcs and any .NET SDK)
const cq = s => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
out('ports/csharp/Rules.cs', `// ${NOTE}
using System.Collections.Generic;

namespace Sweepstakes
{
    public sealed class Table
    {
        public readonly string Id, Name, Blurb; public readonly int W, H, M, Gems; public readonly double Lim, Prog, Min, Cap, Cost;
        public Table(string id, string name, int w, int h, int m, int gems, double lim, double prog, double min, double cap, double cost, string blurb)
        { Id = id; Name = name; W = w; H = h; M = m; Gems = gems; Lim = lim; Prog = prog; Min = min; Cap = cap; Cost = cost; Blurb = blurb; }
    }
    public sealed class GemTier { public readonly string K, Name; public readonly double X, W; public GemTier(string k, double x, double w, string name) { K = k; X = x; W = w; Name = name; } }
    public sealed class Style { public readonly string Who; public readonly double Boom, Lo, Hi; public Style(string who, double boom, double lo, double hi) { Who = who; Boom = boom; Lo = lo; Hi = hi; } }
    public sealed class GoldenBoard
    {
        public readonly string Key, Mines, Open; public readonly int Number; public readonly int[] GemAt; public readonly double[] GemX; public readonly string[] FriendWho; public readonly double[] FriendMult;
        public GoldenBoard(string key, int number, string mines, string open, int[] gemAt, double[] gemX, string[] friendWho, double[] friendMult)
        { Key = key; Number = number; Mines = mines; Open = open; GemAt = gemAt; GemX = gemX; FriendWho = friendWho; FriendMult = friendMult; }
    }
    public sealed class GoldenRun
    {
        public readonly string Key, Why; public readonly string[] Moves; public readonly int Revealed; public readonly double Mult;
        public GoldenRun(string key, string[] moves, int revealed, double mult, string why) { Key = key; Moves = moves; Revealed = revealed; Mult = mult; Why = why; }
    }

    public static class Rules
    {
        public const long START = ${START};
        public const double BOOST = ${dbl(BOOST)}, CLEAR = ${dbl(CLEAR)}, GOLDEN = ${dbl(GOLDEN)}, CASINO = ${dbl(CASINO)};
        public static readonly int[] LADDER = { ${LADDER.join(', ')} };
        public static readonly Table[] TABLES = {
${tables.map(t => `            new Table(${cq(t.id)}, ${cq(t.name)}, ${t.w}, ${t.h}, ${t.m}, ${t.gems}, ${dbl(t.lim)}, ${dbl(t.prog)}, ${dbl(t.min)}, ${dbl(t.cap)}, ${dbl(t.cost)}, ${cq(t.blurb)})`).join(',\n')}
        };
        public static readonly GemTier[] GEMS = { ${gems.map(g => `new GemTier(${cq(g.k)}, ${dbl(g.x)}, ${dbl(g.w)}, ${cq(g.name)})`).join(', ')} };
        public static readonly Dictionary<string, string> FRIENDS = new Dictionary<string, string> { ${Object.entries(friends).map(([k, v]) => `{ ${cq(k)}, ${cq(v)} }`).join(', ')} };
        public static readonly string[] SURE = { ${SURE.map(cq).join(', ')} };
        public static readonly string[] QUIPS = {
${QUIPS.map(q => '            ' + cq(q)).join(',\n')}
        };
        public static readonly Dictionary<string, string[][]> LINES = new Dictionary<string, string[][]> {
${Object.entries(lines).map(([k, v]) => `            { ${cq(k)}, new[] { ${v.map(([w, t]) => `new[] { ${cq(w)}, ${cq(t)} }`).join(', ')} } }`).join(',\n')}
        };
        public static readonly int[] DAILY_EPOCH = { ${DAILY.epoch.join(', ')} };
        public const string DAILY_TABLE = ${cq(DAILY.table)}, DAILY_SEED = ${cq(DAILY.seed)}, DAILY_CHAT_SEED = ${cq(DAILY.chatSeed)};
        public const double DAILY_LIMIT = ${dbl(DAILY.limit)}, DAILY_PRIZE = ${dbl(DAILY.prize)};
        public const int DAILY_GEMS = ${DAILY.gems};
        public static readonly Style[] DAILY_STYLES = { ${styles.map(s => `new Style(${cq(s.who)}, ${dbl(s.boom)}, ${dbl(s.lo)}, ${dbl(s.hi)})`).join(', ')} };
        public static readonly GoldenBoard[] GOLDEN_BOARDS = {
${golden.map(g => `            new GoldenBoard(${cq(g.key)}, ${g.number}, ${cq(g.mines)}, ${cq(g.open)}, new[] { ${g.gems.map(([i]) => i).join(', ')} }, new[] { ${g.gems.map(([, x]) => dbl(x)).join(', ')} }, new[] { ${g.friends.map(([w]) => cq(w)).join(', ')} }, new[] { ${g.friends.map(([, m]) => dbl(m)).join(', ')} })`).join(',\n')}
        };
        public static readonly GoldenRun[] GOLDEN_RUNS = {
${runs.map(r => `            new GoldenRun(${cq(r.key)}, new[] { ${r.moves.map(cq).join(', ')} }, ${r.revealed}, ${dbl(r.mult)}, ${cq(r.why)})`).join(',\n')}
        };
    }
}
`);
if (process.argv.includes('--check')) {
  const stale = [...files].filter(([rel, text]) => !existsSync(join(ROOT, rel)) || readFileSync(join(ROOT, rel), 'utf8') !== text).map(([rel]) => rel);
  console.log(stale.length ? `out of date: ${stale.join(', ')} (run: node tools/export_rules.mjs)` : 'ports are up to date with the web game');
  process.exit(stale.length ? 1 : 0);
}
for (const [rel, text] of files) { const p = join(ROOT, rel); mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, text); console.log('wrote', rel); }
for (const r of runs) console.log(`golden run ${r.key}: ${r.why} ×${r.mult} after ${r.moves.length} digs (${r.moves.join(' ')})`);
process.exit(0);
